/// enigma_naming_audit.cpp
/// Naming coverage audit tool.
/// Categorizes every function by name prefix, hashes unnamed functions,
/// traverses the call graph to distinguish missing knowledge / discovery
/// failure / propagation failure, and emits both a human-readable report
/// and a CSV for cross-binary FID-candidate merging.
///
/// Usage: enigma_naming_audit <binary> [--csv <output.csv>]

#include <ghidra/BinaryLoader.h>
#include <ghidra/ProgramDB.h>
#include <ghidra/Memory.h>
#include <ghidra/MemoryBlock.h>
#include <ghidra/FunctionManager.h>
#include <ghidra/Function.h>
#include <ghidra/SymbolTable.h>
#include <ghidra/SymbolUtilities.h>
#include <ghidra/ExternalManager.h>
#include <ghidra/Listing.h>
#include <ghidra/Instruction.h>
#include <ghidra/ProgramAddressFactory.h>
#include <ghidra/AddressSpace.h>
#include <ghidra/AddressRange.h>
#include <ghidra/AutoAnalysisManager.h>
#include <ghidra/TaskMonitor.h>
#include <ghidra/MessageLog.h>
#include <ghidra/ReferenceManager.h>
#include <ghidra/Reference.h>
#include <ghidra/RefType.h>
#include <ghidra/FNV1a64.h>
#include <ghidra/NamingService.h>
#include <ghidra/EntryPointAnalyzer.h>
#include <ghidra/DisassemblyAnalyzer.h>
#include <ghidra/FunctionStartAnalyzer.h>
#include <ghidra/FunctionStartDataPostAnalyzer.h>
#include <ghidra/FunctionStartFuncAnalyzer.h>
#include <ghidra/DataSectionFunctionScannerAnalyzer.h>
#include <ghidra/ApplyDataArchiveAnalyzer.h>
#include <ghidra/MainRecognitionAnalyzer.h>
#include <ghidra/FragmentMergeAnalyzer.h>
#include <ghidra/FidAnalyzer.h>
#include <ghidra/FunctionBodyFinalizer.h>
#include <ghidra/ExternalEntryFunctionAnalyzer.h>
#include <ghidra/FunctionDiscoveryAnalyzer.h>
#include <ghidra/DataRefFunctionAnalyzer.h>
#include <ghidra/PEExceptionAnalyzer.h>
#include <ghidra/ImportThunkAnalyzer.h>
#include <ghidra/ScalarOperandAnalyzer.h>
#include <ghidra/OperandReferenceAnalyzer.h>
#include <ghidra/DataOperandReferenceAnalyzer.h>
#include <ghidra/ConstantPropagationAnalyzer.h>
#include <ghidra/StackReferenceAnalyzer.h>
#include <ghidra/StackVariableAnalyzer.h>

#include <iostream>
#include <fstream>
#include <string>
#include <memory>
#include <map>
#include <set>
#include <vector>
#include <algorithm>
#include <sstream>
#include <iomanip>
#include <cstdlib>

using namespace ghidra;

// ── Auto-generated name prefix list ───────────────────────────────────
static const char* kAutoPrefixes[] = {
    "FUN_", "sub_", "func_start_", "func_call_", "func_jmp_",
    "func_rva_", "func_data_", "func_fallback_", "func_gap_",
    "func_gap_agg_", "func_wrapper_", "func_pdata_", "function_",
    "call_target_", "data_func_", "func_sweep_", "sym_",
    "data_func_", nullptr
};

static bool isAutoGenerated(const std::string& name) {
    return SymbolUtilities::isAutoGeneratedName(name);
}

// Classify a function name into a specific auto-gen category or "named".
// Returns the category label.
static std::string classifyCategory(const std::string& name) {
    if (isAutoGenerated(name)) {
        // Identify the specific prefix
        for (const char** p = kAutoPrefixes; *p; ++p) {
            std::string prefix(*p);
            if (name.compare(0, prefix.size(), prefix) == 0)
                return prefix;
        }
        if (name.empty()) return "empty";
        return "other_auto";
    }
    if (name == "entry") return "entry";
    return "named";
}

// ── Per-function record ───────────────────────────────────────────────
struct FuncRecord {
    uint64_t addr;
    std::string name;
    std::string category;    // specific prefix or "named"
    bool isAuto;
    // Body stats
    int bodySizeBytes;       // address range of body
    int numInstructions;     // count of instructions in body
    // Call-graph stats
    int numCallers;          // references TO this function (flow/call only)
    int numCallees;          // references FROM this function (flow/call only)
    bool callsNamedApi;      // any callee has a non-auto name
    bool calledByNamed;      // any caller has a non-auto name
    // Hash
    uint64_t fnvHash;        // FNV-1a of first 32 bytes
    int hashBytes;           // bytes actually hashed
    // Failure category (for unnamed functions)
    std::string failureType; // "named", "missing_knowledge", "discovery_failure", "propagation_failure"
};

// ── Binary name from path ─────────────────────────────────────────────
static std::string basenameOf(const std::string& path) {
    auto pos = path.find_last_of("/\\");
    return (pos == std::string::npos) ? path : path.substr(pos + 1);
}

// ── Main ──────────────────────────────────────────────────────────────
int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: enigma_naming_audit <binary> [--csv <output.csv>]\n";
        return 1;
    }

    std::string path = argv[1];
    std::string csvPath;
    for (int i = 2; i < argc; i++) {
        if (std::string(argv[i]) == "--csv" && i + 1 < argc) {
            csvPath = argv[++i];
        }
    }

    // ── Load binary ───────────────────────────────────────────────────
    auto loader = createLoader();
    if (!loader || !loader->load(path)) {
        std::cerr << "Failed to load: " << path << "\n";
        return 1;
    }

    auto* ramSpace = new GenericAddressSpace("ram", 64, AddressSpace::TYPE_RAM, 1);
    auto* constSpace = new GenericAddressSpace("const", 64, AddressSpace::TYPE_CONSTANT, 2);
    auto* uniqueSpace = new GenericAddressSpace("unique", 64, AddressSpace::TYPE_UNIQUE, 3);
    auto* regSpace = new GenericAddressSpace("register", 64, AddressSpace::TYPE_REGISTER, 4);
    auto* stackSpace = new GenericAddressSpace("stack", 64, AddressSpace::TYPE_STACK, 5);

    auto prog = std::make_unique<ProgramDB>("naming_audit", nullptr, nullptr);
    auto* addrFactory = dynamic_cast<ProgramAddressFactory*>(prog->getAddressFactory());
    if (addrFactory) {
        addrFactory->addAddressSpace(ramSpace);
        addrFactory->addAddressSpace(constSpace);
        addrFactory->addAddressSpace(uniqueSpace);
        addrFactory->addAddressSpace(regSpace);
        addrFactory->addAddressSpace(stackSpace);
        addrFactory->setDefaultSpace(ramSpace);
    }

    if (!loader->populateProgram(prog.get())) {
        std::cerr << "populateProgram failed\n";
        return 1;
    }

    // ── Function discovery ────────────────────────────────────────────
    auto* fm = prog->getFunctionManager();
    auto* listing = prog->getListing();
    auto* refMgr = prog->getReferenceManager();
    auto* memory = prog->getMemory();

    {
        FunctionDiscoveryOptions fdOpts;
        fdOpts.includeExternalInFunctionManager = true;
        FunctionDiscoveryAnalyzer fdAnalyzer(fdOpts);
        fdAnalyzer.analyzeLoader(*loader);
        if (fm && ramSpace) {
            fdAnalyzer.applyTo(*fm, ramSpace);
        }
    }

    // ── Full analysis pipeline ────────────────────────────────────────
    auto analysisMgr = std::make_unique<AutoAnalysisManager>(prog.get());
    analysisMgr->registerAnalyzer(std::make_unique<EntryPointAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<DisassemblyAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FunctionStartAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<DataSectionFunctionScannerAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FunctionStartDataPostAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FunctionStartFuncAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<ApplyDataArchiveAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<ExternalEntryFunctionAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<PEExceptionAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<DataRefFunctionAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<ScalarOperandAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<OperandReferenceAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<DataOperandReferenceAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<ConstantPropagationAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<StackReferenceAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<StackVariableAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FragmentMergeAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<ImportThunkAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FidAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<MainRecognitionAnalyzer>());
    analysisMgr->registerAnalyzer(std::make_unique<FunctionBodyFinalizer>());

    analysisMgr->analyze(&ghidra::getDummyMonitor());

    // ── Gather export/import address sets ─────────────────────────────
    std::set<uint64_t> exportAddrs;
    std::set<uint64_t> importAddrs;
    {
        auto exps = loader->getExports();
        for (auto& e : exps) exportAddrs.insert(e.address);
        auto imps = loader->getImports();
        for (auto& i : imps) importAddrs.insert(i.address);
    }

    // ── Collect and classify all functions ────────────────────────────
    std::vector<FuncRecord> records;
    // For instruction count per function body
    std::map<uint64_t, int> instrCountMap;

    if (listing) {
        auto allInstrs = listing->getAllInstructions();
        for (auto* inst : allInstrs) {
            if (!inst) continue;
            uint64_t addr = inst->getAddress().getOffset();
            if (auto* func = fm->getFunctionContaining(inst->getAddress())) {
                uint64_t entry = func->getEntryPoint().getOffset();
                instrCountMap[entry]++;
            }
        }
    }

    if (fm) {
        auto fit = fm->getFunctions(true);
        while (fit.hasNext()) {
            auto* f = fit.next();
            if (!f) continue;

            FuncRecord r{};
            r.addr = f->getEntryPoint().getOffset();
            r.name = f->getName();
            r.category = classifyCategory(r.name);
            r.isAuto = isAutoGenerated(r.name);

            // Body size
            AddressSet bodySet = f->getBody();
            r.bodySizeBytes = 0;
            if (bodySet.getNumAddressRanges() > 0) {
                auto* it = bodySet.getAddressRanges();
                while (it->hasNext()) {
                    AddressRange rng = it->next();
                    r.bodySizeBytes += static_cast<int>(
                        rng.getMaxAddress().getOffset() - rng.getMinAddress().getOffset());
                }
            }

            // Instruction count
            r.numInstructions = instrCountMap.count(r.addr) ? instrCountMap[r.addr] : 0;

            // Call-graph: find callers and callees via ReferenceManager
            r.numCallers = 0;
            r.numCallees = 0;
            r.callsNamedApi = false;
            r.calledByNamed = false;

            if (refMgr) {
                // Callers (references TO this function that are flow/call)
                auto refsTo = refMgr->getReferencesTo(f->getEntryPoint());
                std::set<uint64_t> callerAddrs;
                for (auto* ref : refsTo) {
                    if (!ref) continue;
                    const RefType* rt = ref->getReferenceType();
                    if (rt && rt->isFlow()) {
                        uint64_t fromAddr = ref->getFromAddress().getOffset();
                        if (callerAddrs.insert(fromAddr).second) {
                            r.numCallers++;
                            if (auto* callerFunc = fm->getFunctionContaining(ref->getFromAddress())) {
                                if (!isAutoGenerated(callerFunc->getName()) && callerFunc->getName() != "entry") {
                                    r.calledByNamed = true;
                                }
                            }
                        }
                    }
                }

                // Callees (flow references FROM this function that are calls)
                auto refsFrom = refMgr->getFlowReferencesFrom(f->getEntryPoint());
                std::set<uint64_t> calleeAddrs;
                for (auto* ref : refsFrom) {
                    if (!ref) continue;
                    const RefType* rt = ref->getReferenceType();
                    if (rt && rt->isCall()) {
                        uint64_t toAddr = ref->getToAddress().getOffset();
                        if (calleeAddrs.insert(toAddr).second) {
                            r.numCallees++;
                            if (auto* calleeFunc = fm->getFunctionContaining(ref->getToAddress())) {
                                if (!isAutoGenerated(calleeFunc->getName()) && calleeFunc->getName() != "entry") {
                                    r.callsNamedApi = true;
                                }
                            }
                        }
                    }
                }
            }

            // FNV-1a hash of first 32 bytes
            r.hashBytes = 0;
            r.fnvHash = 0;
            if (memory) {
                uint8_t buf[32];
                int bytesRead = memory->getBytes(f->getEntryPoint(), buf, sizeof(buf));
                if (bytesRead > 0) {
                    r.fnvHash = FNV1a64::hash(buf, bytesRead);
                    r.hashBytes = bytesRead;
                }
            }

            // Failure classification (only meaningful for auto-generated names)
            if (!r.isAuto) {
                r.failureType = "named";
            } else if (r.numInstructions == 0 && r.bodySizeBytes == 0) {
                r.failureType = "discovery_failure";
            } else if (r.callsNamedApi || r.calledByNamed) {
                r.failureType = "propagation_failure";
            } else {
                r.failureType = "missing_knowledge";
            }

            records.push_back(r);
        }
    }

    // ── Aggregate statistics ──────────────────────────────────────────
    std::string binaryName = basenameOf(path);

    // Category counts
    std::map<std::string, int> categoryCounts;
    std::map<std::string, int> failureCounts;
    std::map<std::string, int> namedSourceCounts;
    int totalFunctions = static_cast<int>(records.size());
    int namedCount = 0;
    int autoCount = 0;

    for (auto& r : records) {
        categoryCounts[r.category]++;
        failureCounts[r.failureType]++;
        if (!r.isAuto) {
            namedCount++;
            if (exportAddrs.count(r.addr)) namedSourceCounts["export"]++;
            else if (importAddrs.count(r.addr)) namedSourceCounts["import"]++;
            else if (r.name == "entry") namedSourceCounts["entry"]++;
            else namedSourceCounts["other_named"]++;
        } else {
            autoCount++;
        }
    }

    // ── Human-readable report ─────────────────────────────────────────
    std::cout << "=================================================================\n";
    std::cout << "  Naming Coverage Audit: " << binaryName << "\n";
    std::cout << "=================================================================\n\n";

    std::cout << "Total functions:    " << totalFunctions << "\n";
    std::cout << "Named functions:    " << namedCount << "  ("
              << std::fixed << std::setprecision(1)
              << (100.0 * namedCount / totalFunctions) << "%)\n";
    std::cout << "Auto-generated:     " << autoCount << "  ("
              << (100.0 * autoCount / totalFunctions) << "%)\n\n";

    // Category breakdown (sorted by count descending)
    std::cout << "Category Breakdown:\n";
    std::vector<std::pair<std::string, int>> sortedCats(categoryCounts.begin(), categoryCounts.end());
    std::sort(sortedCats.begin(), sortedCats.end(),
              [](const auto& a, const auto& b) { return a.second > b.second; });
    for (auto& [cat, count] : sortedCats) {
        std::cout << "  " << std::left << std::setw(24) << cat
                  << std::right << std::setw(6) << count
                  << "  (" << std::fixed << std::setprecision(1)
                  << (100.0 * count / totalFunctions) << "%)\n";
    }

    // Failure breakdown (only for auto-generated functions)
    std::cout << "\nFailure Breakdown (auto-generated functions only):\n";
    std::vector<std::pair<std::string, int>> sortedFails(failureCounts.begin(), failureCounts.end());
    std::sort(sortedFails.begin(), sortedFails.end(),
              [](const auto& a, const auto& b) { return a.second > b.second; });
    for (auto& [fail, count] : sortedFails) {
        std::cout << "  " << std::left << std::setw(28) << fail
                  << std::right << std::setw(6) << count
                  << "  (" << std::fixed << std::setprecision(1)
                  << (100.0 * count / autoCount) << "%)\n";
    }

    // Named source breakdown
    std::cout << "\nNamed Function Sources:\n";
    std::vector<std::pair<std::string, int>> sortedSources(namedSourceCounts.begin(), namedSourceCounts.end());
    std::sort(sortedSources.begin(), sortedSources.end(),
              [](const auto& a, const auto& b) { return a.second > b.second; });
    for (auto& [src, count] : sortedSources) {
        std::cout << "  " << std::left << std::setw(24) << src
                  << std::right << std::setw(6) << count << "\n";
    }

    // Cross-binary signature summary
    std::map<uint64_t, int> hashFreq;
    std::map<uint64_t, int> hashSizes;
    for (auto& r : records) {
        if (r.isAuto && r.fnvHash != 0) {
            hashFreq[r.fnvHash]++;
            hashSizes[r.fnvHash] = r.hashBytes;
        }
    }
    int uniqueHashes = static_cast<int>(hashFreq.size());
    int singletons = 0;
    for (auto& [h, c] : hashFreq) {
        if (c == 1) singletons++;
    }

    std::cout << "\nUnnamed Signature Summary:\n";
    std::cout << "  Total unique hashes:   " << uniqueHashes << "\n";
    std::cout << "  Singletons (1 func):   " << singletons << "\n";
    std::cout << "  Repeated (2+ funcs):   " << (uniqueHashes - singletons) << "\n";

    // Top repeated hashes (within this binary)
    std::vector<std::pair<uint64_t, int>> sortedHashes(hashFreq.begin(), hashFreq.end());
    std::sort(sortedHashes.begin(), sortedHashes.end(),
              [](const auto& a, const auto& b) { return a.second > b.second; });
    int showCount = std::min(20, static_cast<int>(sortedHashes.size()));
    if (showCount > 0) {
        std::cout << "\nTop Repeated Unnamed Signatures (within this binary):\n";
        for (int i = 0; i < showCount; i++) {
            auto& [h, c] = sortedHashes[i];
            std::cout << "  #" << std::setw(2) << (i + 1) << "  hash=0x"
                      << std::hex << std::setw(16) << std::setfill('0') << h
                      << std::dec << std::setfill(' ')
                      << "  size=" << hashSizes[h]
                      << "  count=" << c << "\n";
        }
    }

    // Top propagation-failure functions (unnamed but called by named)
    std::vector<FuncRecord*> propFailFuncs;
    for (auto& r : records) {
        if (r.failureType == "propagation_failure") {
            propFailFuncs.push_back(&r);
        }
    }
    std::sort(propFailFuncs.begin(), propFailFuncs.end(),
              [](const FuncRecord* a, const FuncRecord* b) {
                  return a->numCallers > b->numCallers;
              });
    int propShowCount = std::min(20, static_cast<int>(propFailFuncs.size()));
    if (propShowCount > 0) {
        std::cout << "\nTop Propagation-Failure Candidates (unnamed but called by named function):\n";
        for (int i = 0; i < propShowCount; i++) {
            auto* r = propFailFuncs[i];
            std::cout << "  0x" << std::hex << r->addr << std::dec
                      << "  callers=" << r->numCallers
                      << "  callees=" << r->numCallees
                      << "  callsNamed=" << (r->callsNamedApi ? "Y" : "N")
                      << "  cat=" << r->category << "\n";
        }
    }

    std::cout << "\n=================================================================\n";

    // ── CSV output ────────────────────────────────────────────────────
    if (!csvPath.empty()) {
        std::ofstream csv(csvPath);
        if (csv.is_open()) {
            csv << "binary,addr,name,category,auto,body_size,instrs,callers,callees,"
                   "calls_named,called_by_named,hash,hash_bytes,failure\n";
            for (auto& r : records) {
                csv << binaryName
                    << ",0x" << std::hex << r.addr
                    << "," << r.name
                    << "," << r.category
                    << "," << (r.isAuto ? "Y" : "N")
                    << "," << r.bodySizeBytes
                    << "," << r.numInstructions
                    << "," << r.numCallers
                    << "," << r.numCallees
                    << "," << (r.callsNamedApi ? "Y" : "N")
                    << "," << (r.calledByNamed ? "Y" : "N")
                    << ",0x" << std::setw(16) << std::setfill('0') << r.fnvHash
                    << std::dec << std::setfill(' ')
                    << "," << r.hashBytes
                    << "," << r.failureType << "\n";
            }
            csv.close();
            std::cerr << "CSV written to: " << csvPath << "\n";
        } else {
            std::cerr << "Failed to open CSV: " << csvPath << "\n";
        }
    }

    return 0;
}
