/* ###
 * IP: GHIDRA (translated to C++ for Enigma Engine)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 */
/// \file ProgramChangeRecord.h
/// \brief Event data for a change in a Program.
#pragma once

#include "ghidra/Address.h"
#include <string>

namespace ghidra {

/**
 * Event data for a DomainObjectChangeEvent generated by a Program.
 * Translated from: ghidra.program.util.ProgramChangeRecord
 *
 * Note: in the C++ port this is a standalone value type (the Java class
 * extends DomainObjectChangeRecord which is not ported).
 */
class ProgramChangeRecord {
public:
    enum class ProgramEvent {
        UNKNOWN,
        CODE_ADDED,
        CODE_REMOVED,
        CODE_MODIFIED,
        SYMBOL_ADDED,
        SYMBOL_REMOVED,
        SYMBOL_RENAMED,
        FUNCTION_ADDED,
        FUNCTION_REMOVED,
        FUNCTION_CHANGED,
        TYPES_CHANGED,
    };

    ProgramChangeRecord(ProgramEvent eventType,
                        const Address& start, const Address& end, void* affected,
                        const std::string& oldValue, const std::string& newValue);

    ProgramEvent getEventType() const { return eventType_; }
    const Address& getStart() const { return start_; }
    const Address& getEnd() const { return end_; }
    void* getObject() const { return affected_; }
    const std::string& getOldValue() const { return oldValue_; }
    const std::string& getNewValue() const { return newValue_; }

    std::string toString() const;

private:
    ProgramEvent eventType_;
    Address start_;
    Address end_;
    void* affected_;
    std::string oldValue_;
    std::string newValue_;
};

} // namespace ghidra
