// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FKS_FBSCHEMA_H_
#define FLATBUFFERS_GENERATED_FKS_FBSCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace fbschema {

struct FkHashQuad;

struct FkHashQuadV2;

struct FksFunction;
struct FksFunctionBuilder;

struct FksLibraryMeta;
struct FksLibraryMetaBuilder;

struct FksRelation;
struct FksRelationBuilder;

struct FkCandidate;
struct FkCandidateBuilder;

struct FkCandidateList;
struct FkCandidateListBuilder;

struct FksLibrary;
struct FksLibraryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) FkHashQuad FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t full_hash_;
  uint64_t short_hash_;
  uint64_t mnem_hash_;
  uint64_t call_hash_;

 public:
  FkHashQuad()
      : full_hash_(0),
        short_hash_(0),
        mnem_hash_(0),
        call_hash_(0) {
  }
  FkHashQuad(uint64_t _full_hash, uint64_t _short_hash, uint64_t _mnem_hash, uint64_t _call_hash)
      : full_hash_(::flatbuffers::EndianScalar(_full_hash)),
        short_hash_(::flatbuffers::EndianScalar(_short_hash)),
        mnem_hash_(::flatbuffers::EndianScalar(_mnem_hash)),
        call_hash_(::flatbuffers::EndianScalar(_call_hash)) {
  }
  uint64_t full_hash() const {
    return ::flatbuffers::EndianScalar(full_hash_);
  }
  uint64_t short_hash() const {
    return ::flatbuffers::EndianScalar(short_hash_);
  }
  uint64_t mnem_hash() const {
    return ::flatbuffers::EndianScalar(mnem_hash_);
  }
  uint64_t call_hash() const {
    return ::flatbuffers::EndianScalar(call_hash_);
  }
};
FLATBUFFERS_STRUCT_END(FkHashQuad, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) FkHashQuadV2 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t full_hash_;
  uint64_t short_hash_;
  uint64_t mnem_hash_;
  uint64_t call_hash_;

 public:
  FkHashQuadV2()
      : full_hash_(0),
        short_hash_(0),
        mnem_hash_(0),
        call_hash_(0) {
  }
  FkHashQuadV2(uint64_t _full_hash, uint64_t _short_hash, uint64_t _mnem_hash, uint64_t _call_hash)
      : full_hash_(::flatbuffers::EndianScalar(_full_hash)),
        short_hash_(::flatbuffers::EndianScalar(_short_hash)),
        mnem_hash_(::flatbuffers::EndianScalar(_mnem_hash)),
        call_hash_(::flatbuffers::EndianScalar(_call_hash)) {
  }
  uint64_t full_hash() const {
    return ::flatbuffers::EndianScalar(full_hash_);
  }
  uint64_t short_hash() const {
    return ::flatbuffers::EndianScalar(short_hash_);
  }
  uint64_t mnem_hash() const {
    return ::flatbuffers::EndianScalar(mnem_hash_);
  }
  uint64_t call_hash() const {
    return ::flatbuffers::EndianScalar(call_hash_);
  }
};
FLATBUFFERS_STRUCT_END(FkHashQuadV2, 32);

struct FksFunction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FksFunctionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_NAME = 6,
    VT_NAME_DEMANGLED = 8,
    VT_HASHES = 10,
    VT_HASHES_V2 = 12,
    VT_BODY_SIZE = 14,
    VT_INSTR_COUNT = 16,
    VT_CALL_COUNT = 18,
    VT_BASIC_BLOCKS = 20,
    VT_CYCLOMATIC = 22,
    VT_HAS_FRAME = 24,
    VT_EXPORTED = 26,
    VT_VIRTUAL_ADDRESS = 28,
    VT_NAMESPACE_PATH = 30,
    VT_IS_THUNK = 32,
    VT_IS_LIBRARY = 34,
    VT_IS_EXTERNAL = 36,
    VT_SIGNATURE = 38
  };
  uint64_t uid() const {
    return GetField<uint64_t>(VT_UID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *name_demangled() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME_DEMANGLED);
  }
  const fbschema::FkHashQuad *hashes() const {
    return GetStruct<const fbschema::FkHashQuad *>(VT_HASHES);
  }
  const fbschema::FkHashQuadV2 *hashes_v2() const {
    return GetStruct<const fbschema::FkHashQuadV2 *>(VT_HASHES_V2);
  }
  uint32_t body_size() const {
    return GetField<uint32_t>(VT_BODY_SIZE, 0);
  }
  uint16_t instr_count() const {
    return GetField<uint16_t>(VT_INSTR_COUNT, 0);
  }
  uint16_t call_count() const {
    return GetField<uint16_t>(VT_CALL_COUNT, 0);
  }
  uint16_t basic_blocks() const {
    return GetField<uint16_t>(VT_BASIC_BLOCKS, 0);
  }
  uint16_t cyclomatic() const {
    return GetField<uint16_t>(VT_CYCLOMATIC, 0);
  }
  bool has_frame() const {
    return GetField<uint8_t>(VT_HAS_FRAME, 0) != 0;
  }
  bool exported() const {
    return GetField<uint8_t>(VT_EXPORTED, 0) != 0;
  }
  uint64_t virtual_address() const {
    return GetField<uint64_t>(VT_VIRTUAL_ADDRESS, 0);
  }
  const ::flatbuffers::String *namespace_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAMESPACE_PATH);
  }
  bool is_thunk() const {
    return GetField<uint8_t>(VT_IS_THUNK, 0) != 0;
  }
  bool is_library() const {
    return GetField<uint8_t>(VT_IS_LIBRARY, 0) != 0;
  }
  bool is_external() const {
    return GetField<uint8_t>(VT_IS_EXTERNAL, 0) != 0;
  }
  const ::flatbuffers::String *signature() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIGNATURE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_UID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_NAME_DEMANGLED) &&
           verifier.VerifyString(name_demangled()) &&
           VerifyField<fbschema::FkHashQuad>(verifier, VT_HASHES, 8) &&
           VerifyField<fbschema::FkHashQuadV2>(verifier, VT_HASHES_V2, 8) &&
           VerifyField<uint32_t>(verifier, VT_BODY_SIZE, 4) &&
           VerifyField<uint16_t>(verifier, VT_INSTR_COUNT, 2) &&
           VerifyField<uint16_t>(verifier, VT_CALL_COUNT, 2) &&
           VerifyField<uint16_t>(verifier, VT_BASIC_BLOCKS, 2) &&
           VerifyField<uint16_t>(verifier, VT_CYCLOMATIC, 2) &&
           VerifyField<uint8_t>(verifier, VT_HAS_FRAME, 1) &&
           VerifyField<uint8_t>(verifier, VT_EXPORTED, 1) &&
           VerifyField<uint64_t>(verifier, VT_VIRTUAL_ADDRESS, 8) &&
           VerifyOffset(verifier, VT_NAMESPACE_PATH) &&
           verifier.VerifyString(namespace_path()) &&
           VerifyField<uint8_t>(verifier, VT_IS_THUNK, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_LIBRARY, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_EXTERNAL, 1) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyString(signature()) &&
           verifier.EndTable();
  }
};

struct FksFunctionBuilder {
  typedef FksFunction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(uint64_t uid) {
    fbb_.AddElement<uint64_t>(FksFunction::VT_UID, uid, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(FksFunction::VT_NAME, name);
  }
  void add_name_demangled(::flatbuffers::Offset<::flatbuffers::String> name_demangled) {
    fbb_.AddOffset(FksFunction::VT_NAME_DEMANGLED, name_demangled);
  }
  void add_hashes(const fbschema::FkHashQuad *hashes) {
    fbb_.AddStruct(FksFunction::VT_HASHES, hashes);
  }
  void add_hashes_v2(const fbschema::FkHashQuadV2 *hashes_v2) {
    fbb_.AddStruct(FksFunction::VT_HASHES_V2, hashes_v2);
  }
  void add_body_size(uint32_t body_size) {
    fbb_.AddElement<uint32_t>(FksFunction::VT_BODY_SIZE, body_size, 0);
  }
  void add_instr_count(uint16_t instr_count) {
    fbb_.AddElement<uint16_t>(FksFunction::VT_INSTR_COUNT, instr_count, 0);
  }
  void add_call_count(uint16_t call_count) {
    fbb_.AddElement<uint16_t>(FksFunction::VT_CALL_COUNT, call_count, 0);
  }
  void add_basic_blocks(uint16_t basic_blocks) {
    fbb_.AddElement<uint16_t>(FksFunction::VT_BASIC_BLOCKS, basic_blocks, 0);
  }
  void add_cyclomatic(uint16_t cyclomatic) {
    fbb_.AddElement<uint16_t>(FksFunction::VT_CYCLOMATIC, cyclomatic, 0);
  }
  void add_has_frame(bool has_frame) {
    fbb_.AddElement<uint8_t>(FksFunction::VT_HAS_FRAME, static_cast<uint8_t>(has_frame), 0);
  }
  void add_exported(bool exported) {
    fbb_.AddElement<uint8_t>(FksFunction::VT_EXPORTED, static_cast<uint8_t>(exported), 0);
  }
  void add_virtual_address(uint64_t virtual_address) {
    fbb_.AddElement<uint64_t>(FksFunction::VT_VIRTUAL_ADDRESS, virtual_address, 0);
  }
  void add_namespace_path(::flatbuffers::Offset<::flatbuffers::String> namespace_path) {
    fbb_.AddOffset(FksFunction::VT_NAMESPACE_PATH, namespace_path);
  }
  void add_is_thunk(bool is_thunk) {
    fbb_.AddElement<uint8_t>(FksFunction::VT_IS_THUNK, static_cast<uint8_t>(is_thunk), 0);
  }
  void add_is_library(bool is_library) {
    fbb_.AddElement<uint8_t>(FksFunction::VT_IS_LIBRARY, static_cast<uint8_t>(is_library), 0);
  }
  void add_is_external(bool is_external) {
    fbb_.AddElement<uint8_t>(FksFunction::VT_IS_EXTERNAL, static_cast<uint8_t>(is_external), 0);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::String> signature) {
    fbb_.AddOffset(FksFunction::VT_SIGNATURE, signature);
  }
  explicit FksFunctionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FksFunction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FksFunction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FksFunction> CreateFksFunction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name_demangled = 0,
    const fbschema::FkHashQuad *hashes = nullptr,
    const fbschema::FkHashQuadV2 *hashes_v2 = nullptr,
    uint32_t body_size = 0,
    uint16_t instr_count = 0,
    uint16_t call_count = 0,
    uint16_t basic_blocks = 0,
    uint16_t cyclomatic = 0,
    bool has_frame = false,
    bool exported = false,
    uint64_t virtual_address = 0,
    ::flatbuffers::Offset<::flatbuffers::String> namespace_path = 0,
    bool is_thunk = false,
    bool is_library = false,
    bool is_external = false,
    ::flatbuffers::Offset<::flatbuffers::String> signature = 0) {
  FksFunctionBuilder builder_(_fbb);
  builder_.add_virtual_address(virtual_address);
  builder_.add_uid(uid);
  builder_.add_signature(signature);
  builder_.add_namespace_path(namespace_path);
  builder_.add_body_size(body_size);
  builder_.add_hashes_v2(hashes_v2);
  builder_.add_hashes(hashes);
  builder_.add_name_demangled(name_demangled);
  builder_.add_name(name);
  builder_.add_cyclomatic(cyclomatic);
  builder_.add_basic_blocks(basic_blocks);
  builder_.add_call_count(call_count);
  builder_.add_instr_count(instr_count);
  builder_.add_is_external(is_external);
  builder_.add_is_library(is_library);
  builder_.add_is_thunk(is_thunk);
  builder_.add_exported(exported);
  builder_.add_has_frame(has_frame);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FksFunction> CreateFksFunctionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t uid = 0,
    const char *name = nullptr,
    const char *name_demangled = nullptr,
    const fbschema::FkHashQuad *hashes = nullptr,
    const fbschema::FkHashQuadV2 *hashes_v2 = nullptr,
    uint32_t body_size = 0,
    uint16_t instr_count = 0,
    uint16_t call_count = 0,
    uint16_t basic_blocks = 0,
    uint16_t cyclomatic = 0,
    bool has_frame = false,
    bool exported = false,
    uint64_t virtual_address = 0,
    const char *namespace_path = nullptr,
    bool is_thunk = false,
    bool is_library = false,
    bool is_external = false,
    const char *signature = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto name_demangled__ = name_demangled ? _fbb.CreateString(name_demangled) : 0;
  auto namespace_path__ = namespace_path ? _fbb.CreateString(namespace_path) : 0;
  auto signature__ = signature ? _fbb.CreateString(signature) : 0;
  return fbschema::CreateFksFunction(
      _fbb,
      uid,
      name__,
      name_demangled__,
      hashes,
      hashes_v2,
      body_size,
      instr_count,
      call_count,
      basic_blocks,
      cyclomatic,
      has_frame,
      exported,
      virtual_address,
      namespace_path__,
      is_thunk,
      is_library,
      is_external,
      signature__);
}

struct FksLibraryMeta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FksLibraryMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FAMILY = 4,
    VT_VERSION = 6,
    VT_VARIANT = 8,
    VT_COMPILER = 10,
    VT_LANGUAGE = 12,
    VT_DESCRIPTION = 14,
    VT_CREATED = 16
  };
  const ::flatbuffers::String *family() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FAMILY);
  }
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  const ::flatbuffers::String *variant() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VARIANT);
  }
  const ::flatbuffers::String *compiler() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPILER);
  }
  const ::flatbuffers::String *language() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LANGUAGE);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  uint64_t created() const {
    return GetField<uint64_t>(VT_CREATED, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FAMILY) &&
           verifier.VerifyString(family()) &&
           VerifyOffset(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           VerifyOffset(verifier, VT_VARIANT) &&
           verifier.VerifyString(variant()) &&
           VerifyOffset(verifier, VT_COMPILER) &&
           verifier.VerifyString(compiler()) &&
           VerifyOffset(verifier, VT_LANGUAGE) &&
           verifier.VerifyString(language()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint64_t>(verifier, VT_CREATED, 8) &&
           verifier.EndTable();
  }
};

struct FksLibraryMetaBuilder {
  typedef FksLibraryMeta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_family(::flatbuffers::Offset<::flatbuffers::String> family) {
    fbb_.AddOffset(FksLibraryMeta::VT_FAMILY, family);
  }
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(FksLibraryMeta::VT_VERSION, version);
  }
  void add_variant(::flatbuffers::Offset<::flatbuffers::String> variant) {
    fbb_.AddOffset(FksLibraryMeta::VT_VARIANT, variant);
  }
  void add_compiler(::flatbuffers::Offset<::flatbuffers::String> compiler) {
    fbb_.AddOffset(FksLibraryMeta::VT_COMPILER, compiler);
  }
  void add_language(::flatbuffers::Offset<::flatbuffers::String> language) {
    fbb_.AddOffset(FksLibraryMeta::VT_LANGUAGE, language);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(FksLibraryMeta::VT_DESCRIPTION, description);
  }
  void add_created(uint64_t created) {
    fbb_.AddElement<uint64_t>(FksLibraryMeta::VT_CREATED, created, 0);
  }
  explicit FksLibraryMetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FksLibraryMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FksLibraryMeta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FksLibraryMeta> CreateFksLibraryMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> family = 0,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> variant = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compiler = 0,
    ::flatbuffers::Offset<::flatbuffers::String> language = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    uint64_t created = 0) {
  FksLibraryMetaBuilder builder_(_fbb);
  builder_.add_created(created);
  builder_.add_description(description);
  builder_.add_language(language);
  builder_.add_compiler(compiler);
  builder_.add_variant(variant);
  builder_.add_version(version);
  builder_.add_family(family);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FksLibraryMeta> CreateFksLibraryMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *family = nullptr,
    const char *version = nullptr,
    const char *variant = nullptr,
    const char *compiler = nullptr,
    const char *language = nullptr,
    const char *description = nullptr,
    uint64_t created = 0) {
  auto family__ = family ? _fbb.CreateString(family) : 0;
  auto version__ = version ? _fbb.CreateString(version) : 0;
  auto variant__ = variant ? _fbb.CreateString(variant) : 0;
  auto compiler__ = compiler ? _fbb.CreateString(compiler) : 0;
  auto language__ = language ? _fbb.CreateString(language) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return fbschema::CreateFksLibraryMeta(
      _fbb,
      family__,
      version__,
      variant__,
      compiler__,
      language__,
      description__,
      created);
}

struct FksRelation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FksRelationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CALLER_INDEX = 4,
    VT_CALLEE_INDEX = 6
  };
  uint32_t caller_index() const {
    return GetField<uint32_t>(VT_CALLER_INDEX, 0);
  }
  uint32_t callee_index() const {
    return GetField<uint32_t>(VT_CALLEE_INDEX, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CALLER_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_CALLEE_INDEX, 4) &&
           verifier.EndTable();
  }
};

struct FksRelationBuilder {
  typedef FksRelation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_caller_index(uint32_t caller_index) {
    fbb_.AddElement<uint32_t>(FksRelation::VT_CALLER_INDEX, caller_index, 0);
  }
  void add_callee_index(uint32_t callee_index) {
    fbb_.AddElement<uint32_t>(FksRelation::VT_CALLEE_INDEX, callee_index, 0);
  }
  explicit FksRelationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FksRelation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FksRelation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FksRelation> CreateFksRelation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t caller_index = 0,
    uint32_t callee_index = 0) {
  FksRelationBuilder builder_(_fbb);
  builder_.add_callee_index(callee_index);
  builder_.add_caller_index(caller_index);
  return builder_.Finish();
}

struct FkCandidate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FkCandidateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_NAME = 6,
    VT_NAME_DEMANGLED = 8,
    VT_NAMESPACE_PATH = 10,
    VT_LIBRARY_FAMILY = 12,
    VT_LIBRARY_COMPILER = 14,
    VT_BODY_SIZE = 16,
    VT_INSTR_COUNT = 18,
    VT_CALL_COUNT = 20,
    VT_BASIC_BLOCKS = 22,
    VT_CYCLOMATIC = 24,
    VT_HAS_FRAME = 26,
    VT_IS_THUNK = 28,
    VT_IS_LIBRARY = 30,
    VT_SIGNATURE = 32,
    VT_EXPORTED = 34
  };
  uint64_t uid() const {
    return GetField<uint64_t>(VT_UID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *name_demangled() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME_DEMANGLED);
  }
  const ::flatbuffers::String *namespace_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAMESPACE_PATH);
  }
  const ::flatbuffers::String *library_family() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LIBRARY_FAMILY);
  }
  const ::flatbuffers::String *library_compiler() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LIBRARY_COMPILER);
  }
  uint32_t body_size() const {
    return GetField<uint32_t>(VT_BODY_SIZE, 0);
  }
  uint16_t instr_count() const {
    return GetField<uint16_t>(VT_INSTR_COUNT, 0);
  }
  uint16_t call_count() const {
    return GetField<uint16_t>(VT_CALL_COUNT, 0);
  }
  uint16_t basic_blocks() const {
    return GetField<uint16_t>(VT_BASIC_BLOCKS, 0);
  }
  uint16_t cyclomatic() const {
    return GetField<uint16_t>(VT_CYCLOMATIC, 0);
  }
  bool has_frame() const {
    return GetField<uint8_t>(VT_HAS_FRAME, 0) != 0;
  }
  bool is_thunk() const {
    return GetField<uint8_t>(VT_IS_THUNK, 0) != 0;
  }
  bool is_library() const {
    return GetField<uint8_t>(VT_IS_LIBRARY, 0) != 0;
  }
  const ::flatbuffers::String *signature() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIGNATURE);
  }
  bool exported() const {
    return GetField<uint8_t>(VT_EXPORTED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_UID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_NAME_DEMANGLED) &&
           verifier.VerifyString(name_demangled()) &&
           VerifyOffset(verifier, VT_NAMESPACE_PATH) &&
           verifier.VerifyString(namespace_path()) &&
           VerifyOffset(verifier, VT_LIBRARY_FAMILY) &&
           verifier.VerifyString(library_family()) &&
           VerifyOffset(verifier, VT_LIBRARY_COMPILER) &&
           verifier.VerifyString(library_compiler()) &&
           VerifyField<uint32_t>(verifier, VT_BODY_SIZE, 4) &&
           VerifyField<uint16_t>(verifier, VT_INSTR_COUNT, 2) &&
           VerifyField<uint16_t>(verifier, VT_CALL_COUNT, 2) &&
           VerifyField<uint16_t>(verifier, VT_BASIC_BLOCKS, 2) &&
           VerifyField<uint16_t>(verifier, VT_CYCLOMATIC, 2) &&
           VerifyField<uint8_t>(verifier, VT_HAS_FRAME, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_THUNK, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_LIBRARY, 1) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyString(signature()) &&
           VerifyField<uint8_t>(verifier, VT_EXPORTED, 1) &&
           verifier.EndTable();
  }
};

struct FkCandidateBuilder {
  typedef FkCandidate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(uint64_t uid) {
    fbb_.AddElement<uint64_t>(FkCandidate::VT_UID, uid, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(FkCandidate::VT_NAME, name);
  }
  void add_name_demangled(::flatbuffers::Offset<::flatbuffers::String> name_demangled) {
    fbb_.AddOffset(FkCandidate::VT_NAME_DEMANGLED, name_demangled);
  }
  void add_namespace_path(::flatbuffers::Offset<::flatbuffers::String> namespace_path) {
    fbb_.AddOffset(FkCandidate::VT_NAMESPACE_PATH, namespace_path);
  }
  void add_library_family(::flatbuffers::Offset<::flatbuffers::String> library_family) {
    fbb_.AddOffset(FkCandidate::VT_LIBRARY_FAMILY, library_family);
  }
  void add_library_compiler(::flatbuffers::Offset<::flatbuffers::String> library_compiler) {
    fbb_.AddOffset(FkCandidate::VT_LIBRARY_COMPILER, library_compiler);
  }
  void add_body_size(uint32_t body_size) {
    fbb_.AddElement<uint32_t>(FkCandidate::VT_BODY_SIZE, body_size, 0);
  }
  void add_instr_count(uint16_t instr_count) {
    fbb_.AddElement<uint16_t>(FkCandidate::VT_INSTR_COUNT, instr_count, 0);
  }
  void add_call_count(uint16_t call_count) {
    fbb_.AddElement<uint16_t>(FkCandidate::VT_CALL_COUNT, call_count, 0);
  }
  void add_basic_blocks(uint16_t basic_blocks) {
    fbb_.AddElement<uint16_t>(FkCandidate::VT_BASIC_BLOCKS, basic_blocks, 0);
  }
  void add_cyclomatic(uint16_t cyclomatic) {
    fbb_.AddElement<uint16_t>(FkCandidate::VT_CYCLOMATIC, cyclomatic, 0);
  }
  void add_has_frame(bool has_frame) {
    fbb_.AddElement<uint8_t>(FkCandidate::VT_HAS_FRAME, static_cast<uint8_t>(has_frame), 0);
  }
  void add_is_thunk(bool is_thunk) {
    fbb_.AddElement<uint8_t>(FkCandidate::VT_IS_THUNK, static_cast<uint8_t>(is_thunk), 0);
  }
  void add_is_library(bool is_library) {
    fbb_.AddElement<uint8_t>(FkCandidate::VT_IS_LIBRARY, static_cast<uint8_t>(is_library), 0);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::String> signature) {
    fbb_.AddOffset(FkCandidate::VT_SIGNATURE, signature);
  }
  void add_exported(bool exported) {
    fbb_.AddElement<uint8_t>(FkCandidate::VT_EXPORTED, static_cast<uint8_t>(exported), 0);
  }
  explicit FkCandidateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FkCandidate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FkCandidate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FkCandidate> CreateFkCandidate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name_demangled = 0,
    ::flatbuffers::Offset<::flatbuffers::String> namespace_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> library_family = 0,
    ::flatbuffers::Offset<::flatbuffers::String> library_compiler = 0,
    uint32_t body_size = 0,
    uint16_t instr_count = 0,
    uint16_t call_count = 0,
    uint16_t basic_blocks = 0,
    uint16_t cyclomatic = 0,
    bool has_frame = false,
    bool is_thunk = false,
    bool is_library = false,
    ::flatbuffers::Offset<::flatbuffers::String> signature = 0,
    bool exported = false) {
  FkCandidateBuilder builder_(_fbb);
  builder_.add_uid(uid);
  builder_.add_signature(signature);
  builder_.add_body_size(body_size);
  builder_.add_library_compiler(library_compiler);
  builder_.add_library_family(library_family);
  builder_.add_namespace_path(namespace_path);
  builder_.add_name_demangled(name_demangled);
  builder_.add_name(name);
  builder_.add_cyclomatic(cyclomatic);
  builder_.add_basic_blocks(basic_blocks);
  builder_.add_call_count(call_count);
  builder_.add_instr_count(instr_count);
  builder_.add_exported(exported);
  builder_.add_is_library(is_library);
  builder_.add_is_thunk(is_thunk);
  builder_.add_has_frame(has_frame);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FkCandidate> CreateFkCandidateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t uid = 0,
    const char *name = nullptr,
    const char *name_demangled = nullptr,
    const char *namespace_path = nullptr,
    const char *library_family = nullptr,
    const char *library_compiler = nullptr,
    uint32_t body_size = 0,
    uint16_t instr_count = 0,
    uint16_t call_count = 0,
    uint16_t basic_blocks = 0,
    uint16_t cyclomatic = 0,
    bool has_frame = false,
    bool is_thunk = false,
    bool is_library = false,
    const char *signature = nullptr,
    bool exported = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto name_demangled__ = name_demangled ? _fbb.CreateString(name_demangled) : 0;
  auto namespace_path__ = namespace_path ? _fbb.CreateString(namespace_path) : 0;
  auto library_family__ = library_family ? _fbb.CreateString(library_family) : 0;
  auto library_compiler__ = library_compiler ? _fbb.CreateString(library_compiler) : 0;
  auto signature__ = signature ? _fbb.CreateString(signature) : 0;
  return fbschema::CreateFkCandidate(
      _fbb,
      uid,
      name__,
      name_demangled__,
      namespace_path__,
      library_family__,
      library_compiler__,
      body_size,
      instr_count,
      call_count,
      basic_blocks,
      cyclomatic,
      has_frame,
      is_thunk,
      is_library,
      signature__,
      exported);
}

struct FkCandidateList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FkCandidateListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CANDIDATES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FkCandidate>> *candidates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FkCandidate>> *>(VT_CANDIDATES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CANDIDATES) &&
           verifier.VerifyVector(candidates()) &&
           verifier.VerifyVectorOfTables(candidates()) &&
           verifier.EndTable();
  }
};

struct FkCandidateListBuilder {
  typedef FkCandidateList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_candidates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FkCandidate>>> candidates) {
    fbb_.AddOffset(FkCandidateList::VT_CANDIDATES, candidates);
  }
  explicit FkCandidateListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FkCandidateList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FkCandidateList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FkCandidateList> CreateFkCandidateList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FkCandidate>>> candidates = 0) {
  FkCandidateListBuilder builder_(_fbb);
  builder_.add_candidates(candidates);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FkCandidateList> CreateFkCandidateListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbschema::FkCandidate>> *candidates = nullptr) {
  auto candidates__ = candidates ? _fbb.CreateVector<::flatbuffers::Offset<fbschema::FkCandidate>>(*candidates) : 0;
  return fbschema::CreateFkCandidateList(
      _fbb,
      candidates__);
}

struct FksLibrary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FksLibraryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_META = 6,
    VT_FUNCTIONS = 8,
    VT_RELATIONS = 10
  };
  int32_t schema_version() const {
    return GetField<int32_t>(VT_SCHEMA_VERSION, 3);
  }
  const fbschema::FksLibraryMeta *meta() const {
    return GetPointer<const fbschema::FksLibraryMeta *>(VT_META);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksFunction>> *functions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksFunction>> *>(VT_FUNCTIONS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksRelation>> *relations() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksRelation>> *>(VT_RELATIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyOffset(verifier, VT_META) &&
           verifier.VerifyTable(meta()) &&
           VerifyOffset(verifier, VT_FUNCTIONS) &&
           verifier.VerifyVector(functions()) &&
           verifier.VerifyVectorOfTables(functions()) &&
           VerifyOffset(verifier, VT_RELATIONS) &&
           verifier.VerifyVector(relations()) &&
           verifier.VerifyVectorOfTables(relations()) &&
           verifier.EndTable();
  }
};

struct FksLibraryBuilder {
  typedef FksLibrary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(int32_t schema_version) {
    fbb_.AddElement<int32_t>(FksLibrary::VT_SCHEMA_VERSION, schema_version, 3);
  }
  void add_meta(::flatbuffers::Offset<fbschema::FksLibraryMeta> meta) {
    fbb_.AddOffset(FksLibrary::VT_META, meta);
  }
  void add_functions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksFunction>>> functions) {
    fbb_.AddOffset(FksLibrary::VT_FUNCTIONS, functions);
  }
  void add_relations(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksRelation>>> relations) {
    fbb_.AddOffset(FksLibrary::VT_RELATIONS, relations);
  }
  explicit FksLibraryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FksLibrary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FksLibrary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FksLibrary> CreateFksLibrary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t schema_version = 3,
    ::flatbuffers::Offset<fbschema::FksLibraryMeta> meta = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksFunction>>> functions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbschema::FksRelation>>> relations = 0) {
  FksLibraryBuilder builder_(_fbb);
  builder_.add_relations(relations);
  builder_.add_functions(functions);
  builder_.add_meta(meta);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FksLibrary> CreateFksLibraryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t schema_version = 3,
    ::flatbuffers::Offset<fbschema::FksLibraryMeta> meta = 0,
    const std::vector<::flatbuffers::Offset<fbschema::FksFunction>> *functions = nullptr,
    const std::vector<::flatbuffers::Offset<fbschema::FksRelation>> *relations = nullptr) {
  auto functions__ = functions ? _fbb.CreateVector<::flatbuffers::Offset<fbschema::FksFunction>>(*functions) : 0;
  auto relations__ = relations ? _fbb.CreateVector<::flatbuffers::Offset<fbschema::FksRelation>>(*relations) : 0;
  return fbschema::CreateFksLibrary(
      _fbb,
      schema_version,
      meta,
      functions__,
      relations__);
}

inline const fbschema::FksLibrary *GetFksLibrary(const void *buf) {
  return ::flatbuffers::GetRoot<fbschema::FksLibrary>(buf);
}

inline const fbschema::FksLibrary *GetSizePrefixedFksLibrary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fbschema::FksLibrary>(buf);
}

inline bool VerifyFksLibraryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbschema::FksLibrary>(nullptr);
}

inline bool VerifySizePrefixedFksLibraryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbschema::FksLibrary>(nullptr);
}

inline void FinishFksLibraryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbschema::FksLibrary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFksLibraryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbschema::FksLibrary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbschema

#endif  // FLATBUFFERS_GENERATED_FKS_FBSCHEMA_H_
