/* ###
 * IP: GHIDRA
 *
 * Centralized naming service for the Enigma Engine.
 * All function/symbol renames MUST go through this service.
 */
#pragma once

#include <ghidra/SourceType.h>
#include <string>
#include <vector>
#include <cstdint>
#include <functional>

namespace ghidra {

class Program;
class Function;
class Symbol;
class SymbolTable;
class FunctionManager;

class NamingService {
public:
    explicit NamingService(Program* program);
    ~NamingService() = default;

    // ── Core API ─────────────────────────────────────────────────────────

    struct RenameResult {
        bool success = false;
        bool blocked = false;
        uint64_t address = 0;
        std::string reason;
        std::string oldName;
    };

    RenameResult assignName(Function* func, const std::string& newName, SourceType source);
    RenameResult assignName(Symbol* sym, const std::string& newName, SourceType source);
    RenameResult assignName(uint64_t addr, const std::string& newName, SourceType source);

    void assignAlias(uint64_t addr, const std::string& aliasName, SourceType source);

    bool canRename(const Function* func, SourceType newSource) const;
    bool canRename(const Symbol* sym, SourceType newSource) const;
    bool canRename(uint64_t addr, SourceType newSource) const;

    // ── Auto-generated name detection ────────────────────────────────────

    static bool isAutoGeneratedName(const std::string& name);

    // ── Audit ────────────────────────────────────────────────────────────

    struct AuditEntry {
        uint64_t address = 0;
        std::string oldName;
        std::string newName;
        std::string analyzerName;
        SourceType source = SourceType::DEFAULT;
        bool blocked = false;
        std::string blockReason;
    };

    const std::vector<AuditEntry>& getAuditLog() const { return auditLog_; }
    void clearAuditLog() { auditLog_.clear(); }

    struct AuditSummary {
        int totalRenames = 0;
        int blockedRenames = 0;
        int byAnalyzer = 0;
        int byImporter = 0;
        int byDemangler = 0;
        int byFid = 0;
        int byMainRecognition = 0;
        int byUserDefined = 0;
    };

    AuditSummary getAuditSummary() const;
    std::string generateAuditReport() const;

private:
    Program* program_ = nullptr;
    std::vector<AuditEntry> auditLog_;

    FunctionManager* getFuncMgr() const;
    SymbolTable* getSymTable() const;

    void logRename(uint64_t addr, const std::string& oldName,
                   const std::string& newName, const std::string& analyzer,
                   SourceType source, bool blocked, const std::string& reason);
};

} // namespace ghidra
