/* ###
 * IP: GHIDRA
 *
 * EnigmaExportFidMatches.java
 *
 * Ghidra headless post-script: export all named functions with their raw bytes
 * and comprehensive metadata for the FKS knowledge-extraction pipeline.
 *
 * For each function whose name is NOT auto-generated (not FUN_*, LAB_*, DAT_*),
 * exports: name, entry address offset, body size, raw bytes as hex, demangled name,
 * namespace, thunk/library/external flags, function signature, basic block count,
 * cyclomatic complexity, call count, stack-frame flag, and called-function addresses.
 *
 * Output is JSON written to a file in the current working directory.
 *
 * Usage (headless):
 *   analyzeHeadless.bat <project_dir> <project_name>
 *     -import <binary>
 *     -postScript EnigmaExportFidMatches.java
 *     -scriptPath <path-to-this-directory>
 *     -readOnly
 *     -deleteProject
 *
 * Environment variables:
 *   ENIGMA_GHIDRA_OUTPUT - override output file path
 */
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.address.*;
import ghidra.program.model.symbol.*;
import ghidra.program.model.block.*;
import ghidra.program.model.lang.Register;
import ghidra.app.util.demangler.*;
import ghidra.app.cmd.function.ApplyFunctionSignatureCmd;

import java.io.*;
import java.util.*;
import java.util.regex.Pattern;

public class EnigmaExportFidMatches extends GhidraScript {

    private static final Pattern AUTO_GEN_PATTERN =
        Pattern.compile("^(FUN|LAB|DAT|UNK|EXT|thunk)_[0-9a-fA-F]+$");

    private static boolean isAutoGenerated(String name) {
        if (name == null || name.isEmpty()) return true;
        if (AUTO_GEN_PATTERN.matcher(name).matches()) return true;
        if (name.startsWith("off_") || name.startsWith("byte_") ||
            name.startsWith("word_") || name.startsWith("dword_") ||
            name.startsWith("qword_") || name.startsWith("str_")) return true;
        return false;
    }

    private static String bytesToHex(byte[] data) {
        StringBuilder sb = new StringBuilder(data.length * 2);
        for (byte b : data) {
            sb.append(String.format("%02x", b & 0xff));
        }
        return sb.toString();
    }

    @Override
    protected void run() throws Exception {
        if (currentProgram == null) {
            printerr("No current program");
            return;
        }

        String binaryName = currentProgram.getName();

        // Determine output path
        String outputPath = System.getProperty("user.dir")
            + File.separator + "enigma_ghidra_export.json";
        String envOverride = System.getenv("ENIGMA_GHIDRA_OUTPUT");
        if (envOverride != null && !envOverride.isEmpty()) {
            outputPath = envOverride;
        }

        FunctionManager functionManager = currentProgram.getFunctionManager();
        Listing listing = currentProgram.getListing();
        SymbolTable symTable = currentProgram.getSymbolTable();
        ReferenceManager refMgr = currentProgram.getReferenceManager();
        int totalFuncs = functionManager.getFunctionCount();
        int exportedCount = 0;

        // Build a block model for basic block / cyclomatic analysis
        SimpleBlockModel blockModel = new SimpleBlockModel(currentProgram);

        try (PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(outputPath)))) {
            writer.println("{");
            writer.println("  \"binary\": \"" + escapeJson(binaryName) + "\",");
            writer.println("  \"functions\": [");

            FunctionIterator functions = functionManager.getFunctions(true);
            boolean first = true;

            while (functions.hasNext()) {
                Function func = functions.next();
                String name = func.getName();

                // Skip auto-generated names
                if (isAutoGenerated(name)) continue;

                // Skip external functions (no body bytes)
                if (func.isExternal()) continue;

                long offset = func.getEntryPoint().getOffset();
                AddressSetView body = func.getBody();

                // Compute body size
                long bodySize = 0;
                for (AddressRange range : body.getAddressRanges()) {
                    bodySize += range.getLength();
                }

                if (bodySize < 1 || bodySize > 65536) continue;

                // Extract raw bytes from the function body
                ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
                boolean readOk = true;

                for (AddressRange range : body.getAddressRanges()) {
                    long rangeLen = range.getLength();
                    if (rangeLen > 65536) { readOk = false; break; }

                    byte[] chunk = new byte[(int) rangeLen];
                    int got = currentProgram.getMemory().getBytes(
                        range.getMinAddress(), chunk, 0, (int) rangeLen);
                    if (got < rangeLen) {
                        for (int i = got; i < rangeLen; i++) chunk[i] = 0;
                    }
                    byteStream.write(chunk, 0, (int) rangeLen);
                }

                if (!readOk) continue;

                byte[] rawBytes = byteStream.toByteArray();
                if (rawBytes.length < 1) continue;

                // ── Metadata extraction ────────────────────────────────────

                // Source type
                String sourceType = "unknown";
                try {
                    Symbol sym = symTable.getPrimarySymbol(func.getEntryPoint());
                    if (sym != null) {
                        sourceType = sym.getSource().toString();
                    }
                } catch (Exception e) { /* ignore */ }

                // Count instructions + call count (single pass)
                int instrCount = 0;
                int callCount = 0;
                try {
                    InstructionIterator iter = listing.getInstructions(func.getEntryPoint(), true);
                    while (iter.hasNext()) {
                        Instruction instr = iter.next();
                        if (!body.contains(instr.getAddress())) break;
                        instrCount++;
                        if (instr.getFlowType().isCall()) {
                            callCount++;
                        }
                    }
                } catch (Exception e) {
                    instrCount = 0;
                    callCount = 0;
                }

                // Demangled name and namespace
                String nameDemangled = "";
                String namespacePath = "";
                try {
                    Symbol sym = symTable.getPrimarySymbol(func.getEntryPoint());
                    if (sym != null) {
                        Namespace ns = sym.getParentNamespace();
                        if (ns != null && !ns.isGlobal()) {
                            namespacePath = ns.getNamePath();
                        }
                    }
                    DemangledObject dObj = Demangler.demangle(currentProgram, name);
                    if (dObj != null) {
                        nameDemangled = dObj.getSignature(false);
                        if (namespacePath.isEmpty()) {
                            String nsStr = dObj.getNamespaceString();
                            if (nsStr != null && !nsStr.isEmpty()) {
                                namespacePath = nsStr;
                            }
                        }
                    }
                } catch (Exception e) {
                    // ignore
                }

                // Thunk / library flags
                boolean isThunk = false;
                boolean isLibrary = false;
                try {
                    isThunk = func.isThunk();
                    isLibrary = func.isLibraryFunction();
                } catch (Exception e) {
                    // ignore
                }

                // Function signature
                String signature = "";
                try {
                    signature = func.getPrototypeString();
                } catch (Exception e) {
                    // ignore
                }

                // Basic block count + cyclomatic complexity via block model
                int basicBlocks = 0;
                int cyclomatic = 0;
                try {
                    CodeBlockIterator blocks = blockModel.getCodeBlocksContaining(body, monitor);
                    List<CodeBlock> blockList = new ArrayList<>();
                    while (blocks.hasNext()) {
                        blockList.add(blocks.next());
                    }
                    basicBlocks = blockList.size();

                    // Count edges (call/flow references between blocks in this function)
                    Set<Address> blockStarts = new HashSet<>();
                    for (CodeBlock b : blockList) {
                        blockStarts.add(b.getFirstStartAddress());
                    }

                    int edgeCount = 0;
                    for (CodeBlock b : blockList) {
                        CodeBlockReferenceIterator refs = b.getDestinations(monitor);
                        while (refs.hasNext()) {
                            CodeBlockReference ref = refs.next();
                            Address dest = ref.getDestinationAddress();
                            if (dest != null && body.contains(dest)) {
                                edgeCount++;
                            }
                        }
                    }
                    // M = E - N + 2P; P = 1 for single function
                    cyclomatic = Math.max(0, edgeCount - basicBlocks + 2);
                } catch (Exception e) {
                    basicBlocks = 0;
                    cyclomatic = 0;
                }

                // Has frame
                boolean hasFrame = false;
                try {
                    hasFrame = func.hasStackFrame();
                } catch (Exception e) {
                    // ignore
                }

                // Called functions (addresses of callees within the program)
                List<Long> calledFunctions = new ArrayList<>();
                try {
                    for (Function callee : func.getCalledFunctions(monitor)) {
                        if (callee != null && !callee.isExternal()) {
                            calledFunctions.add(callee.getEntryPoint().getOffset());
                        }
                    }
                } catch (Exception e) {
                    // ignore
                }

                // ── Write JSON ─────────────────────────────────────────────

                if (!first) writer.println(",");
                first = false;

                writer.println("    {");
                writer.println("      \"name\": \"" + escapeJson(name) + "\",");
                writer.println("      \"offset\": " + offset + ",");
                writer.println("      \"size\": " + rawBytes.length + ",");
                writer.println("      \"instr_count\": " + instrCount + ",");
                writer.println("      \"source\": \"" + escapeJson(sourceType) + "\",");
                writer.println("      \"bytes\": \"" + bytesToHex(rawBytes) + "\",");
                writer.println("      \"name_demangled\": \"" + escapeJson(nameDemangled) + "\",");
                writer.println("      \"namespace\": \"" + escapeJson(namespacePath) + "\",");
                writer.println("      \"is_thunk\": " + isThunk + ",");
                writer.println("      \"is_library\": " + isLibrary + ",");
                writer.println("      \"is_external\": false,");
                writer.println("      \"signature\": \"" + escapeJson(signature) + "\",");
                writer.println("      \"basic_blocks\": " + basicBlocks + ",");
                writer.println("      \"cyclomatic\": " + cyclomatic + ",");
                writer.println("      \"call_count\": " + callCount + ",");
                writer.println("      \"has_frame\": " + hasFrame + ",");
                writer.print("      \"called_functions\": [");
                for (int i = 0; i < calledFunctions.size(); i++) {
                    if (i > 0) writer.print(", ");
                    writer.print(calledFunctions.get(i));
                }
                writer.println("]");
                writer.print("    }");
                exportedCount++;
            }

            writer.println();
            writer.println("  ],");
            writer.println("  \"total_functions\": " + totalFuncs + ",");
            writer.println("  \"exported_functions\": " + exportedCount);
            writer.println("}");
        }

        println("EnigmaExportFidMatches: " + binaryName);
        println("  Total functions: " + totalFuncs);
        println("  Exported (named): " + exportedCount);
        println("  Output: " + outputPath);
    }

    private static String escapeJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
