#include <ghidra/FidAnalyzer.h>
#include <ghidra/Program.h>
#include <ghidra/ProgramAddressFactory.h>
#include <ghidra/AddressSpace.h>
#include <ghidra/Memory.h>
#include <ghidra/MemoryBlock.h>
#include <ghidra/Listing.h>
#include <ghidra/Instruction.h>
#include <ghidra/Reference.h>
#include <ghidra/ReferenceManager.h>
#include <ghidra/FunctionManager.h>
#include <ghidra/Function.h>
#include <ghidra/FunctionIterator.h>
#include <ghidra/SymbolTable.h>
#include <ghidra/Symbol.h>
#include <ghidra/NamingService.h>
#include <ghidra/TaskMonitor.h>
#include <ghidra/MessageLog.h>
#include <ghidra/Msg.h>
#include <ghidra/FunctionFingerprint.h>
#include <ghidra/KnownFunctionHashes.h>
#include <ghidra/storage/FksIndexManager.h>
#include <ghidra/storage/FksRepository.h>
#include <flatbuffers/flatbuffers.h>
#include <flatbuffers/verifier.h>
#include "fks_generated.h"
#include <cstdint>
#include <vector>
#include <string>
#include <unordered_map>
#include <set>
#include <algorithm>

namespace ghidra {

FidAnalyzer::FidAnalyzer()
    : AbstractAnalyzer("Function ID",
                       "Names CRT startup and helper functions by tracing call chains from the entry point and checking references to named import thunks.",
                       AnalyzerType::BYTE_ANALYZER) {
    setPriority(AnalysisPriority::FUNCTION_ID_ANALYSIS);
    setDefaultEnablement(true);
    setSupportsOneTimeAnalysis(true);
}

bool FidAnalyzer::canAnalyze(Program* program) const {
    return program != nullptr;
}

bool FidAnalyzer::added(Program* program, const AddressSetView& set,
                         TaskMonitor* monitor, MessageLog& log) {
    if (!program || !monitor) return true;
    monitor->setMessage("Identifying library functions via call-chain analysis...");

    FunctionManager* funcMgr = program->getFunctionManager();
    SymbolTable* symTable = program->getSymbolTable();
    Listing* listing = program->getListing();
    ReferenceManager* refMgr = program->getReferenceManager();
    Memory* memory = program->getMemory();
    AddressSpace* defaultSpace = const_cast<AddressSpace*>(
        program->getAddressFactory()->getDefaultAddressSpace());
    if (!funcMgr || !symTable || !listing || !refMgr) return true;

    // Cache all functions in sorted order once, reuse across all steps.
    FunctionIterator fitAll = funcMgr->getFunctions(true);
    std::vector<Function*> allFunctions;
    while (fitAll.hasNext()) {
        Function* f = fitAll.next();
        if (f) allFunctions.push_back(f);
    }
    if (allFunctions.empty()) return true;

    int identified = 0;

    NamingService naming(program);

    // Rename helper — uses NamingService for all naming decisions.
    auto tryRename = [&](uint64_t off, const std::string& newName) -> bool {
        if (off == 0) return false;
        Address addr(defaultSpace, static_cast<int64_t>(off));
        Function* func = funcMgr->getFunctionAt(addr);
        if (!func) return false;

        std::string cur = func->getName();
        if (!cur.empty() && !NamingService::isAutoGeneratedName(cur)) {
            if (cur != "entry" && cur != "main") return false;
        }

        auto result = naming.assignName(func, newName, SourceType::ANALYSIS);
        naming.assignAlias(off, newName, SourceType::ANALYSIS);

        if (result.success) {
            Msg::info("FidAnalyzer", "renamed 0x" + std::to_string(off) +
                      " " + cur + " -> " + newName);
            log.append("FidAnalyzer: renamed 0x" + std::to_string(off) +
                       " " + cur + " -> " + newName);
        }
        return result.success;
    };

    // Shared state for FKS lookups (used in Step 0 and Step 9)
    FunctionFingerprinter fingerprinter;
    std::string fksDir = storage::FksRepository::getFksDirFromEnv();
    bool fksAvailable = storage::FksIndexManager::indexExists(fksDir);

    // Extract family name from program name (e.g., "kernel32.dll" -> "kernel32")
    std::string familyName;
    {
        std::string progName = program->getName();
        auto dot = progName.rfind('.');
        if (dot != std::string::npos) progName = progName.substr(0, dot);
        auto slash = progName.rfind('\\');
        if (slash != std::string::npos) progName = progName.substr(slash + 1);
        slash = progName.rfind('/');
        if (slash != std::string::npos) progName = progName.substr(slash + 1);
        familyName = progName;
    }

    // Collect all FKS candidates for a function from all hash types.
    // Returns ALL candidates from the first matching hash type (preserving priority order).
    auto collectFksCandidates = [&](const FunctionFingerprint& fp, Function* func)
        -> std::vector<storage::CandidateInfo>
    {
        std::vector<storage::CandidateInfo> result;
        std::vector<uint8_t> data;

        if (fp.v2.shortHash != 0) {
            data = storage::FksIndexManager::lookupByShortHashV2(fksDir, fp.v2.shortHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }
        if (result.empty() && fp.v2.fullHash != 0 && fp.v2.fullHash != fp.v2.shortHash) {
            data = storage::FksIndexManager::lookupByFullHashV2(fksDir, fp.v2.fullHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }
        if (result.empty() && fp.v2.mnemHash != 0) {
            data = storage::FksIndexManager::lookupByMnemHashV2(fksDir, fp.v2.mnemHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }
        if (result.empty() && fp.v2.callHash != 0) {
            data = storage::FksIndexManager::lookupByCallHashV2(fksDir, fp.v2.callHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }

        if (result.empty() && fp.v1.fullHash != 0) {
            data = storage::FksIndexManager::lookupByFullHash(fksDir, fp.v1.fullHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }
        if (result.empty() && fp.v1.shortHash != 0 && fp.v1.shortHash != fp.v1.fullHash) {
            data = storage::FksIndexManager::lookupByShortHash(fksDir, fp.v1.shortHash);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }
        if (result.empty()) {
            uint32_t bodySize = static_cast<uint32_t>(func->getBody().getNumAddresses());
            uint16_t instrCount = static_cast<uint16_t>(
                listing->getInstructions(func->getBody()).size());
            if (bodySize > 0 && instrCount > 0) {
                uint64_t composite = (static_cast<uint64_t>(bodySize) << 32) | instrCount;
                data = storage::FksIndexManager::lookupByBodyInstr(fksDir, composite);
                result = storage::FksIndexManager::extractAllCandidates(data);
            }
        }

        if (result.empty() && !familyName.empty()) {
            uint64_t funcAddr = func->getEntryPoint().getOffset();
            data = storage::FksIndexManager::lookupByAddress(fksDir, familyName, funcAddr);
            result = storage::FksIndexManager::extractAllCandidates(data);
        }

        return result;
    };

    // Pending FKS candidates that must be ranked by Step 11 before any rename.
    // Key: function address. Value: all candidates from hash lookup.
    std::unordered_map<uint64_t, std::vector<storage::CandidateInfo>> pendingFksCandidates;

    // Step 0: Collect FKS candidates from hash lookups (NO RENAME — deferred to Step 11).
    // KnownFunctionHashes (in-process built-in) still renamed immediately.
    {
        KnownFunctionHashes knownHashes;

        for (Function* f : allFunctions) {
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            FunctionFingerprint fp = fingerprinter.compute(f, program);
            if (fp.v1.fullHash == 0) continue;

            // KnownFunctionHashes: fast in-process, rename immediately
            const char* matchedName = knownHashes.lookup(fp.v1.fullHash, 0);
            if (matchedName) {
                uint64_t a = f->getEntryPoint().getOffset();
                if (tryRename(a, matchedName)) ++identified;
                continue;
            }

            // FKS: collect ALL candidates, defer rename to Step 11 for proper ranking
            if (fksAvailable) {
                auto candidates = collectFksCandidates(fp, f);
                if (!candidates.empty()) {
                    uint64_t a = f->getEntryPoint().getOffset();
                    pendingFksCandidates[a] = std::move(candidates);
                }
            }
        }
    }

    // Step 1: Build call + reverse call graph from references
    std::unordered_map<uint64_t, std::vector<uint64_t>> callGraph;
    std::unordered_map<uint64_t, std::vector<uint64_t>> reverseCallGraph;
    std::set<uint64_t> entryPoints;

    for (Function* f : allFunctions) {
        entryPoints.insert(f->getEntryPoint().getOffset());
    }

    // Iterate all references instead of all instructions + per-instr ref lookup.
    // Eliminates 1.27M getAllInstructions copy + 1.27M getReferencesFrom(toString()) calls.
    std::vector<Reference*> allRefs = refMgr->getAllReferences();
    for (Reference* ref : allRefs) {
        if (!ref) continue;
        const RefType* rt = ref->getReferenceType();
        if (!rt || !rt->isCall()) continue;

        uint64_t callee = ref->getToAddress().getOffset();
        if (callee == 0) continue;

        uint64_t fromAddr = ref->getFromAddress().getOffset();
        auto it = entryPoints.upper_bound(fromAddr);
        if (it == entryPoints.begin()) continue;
        --it;
        uint64_t caller = *it;

        callGraph[caller].push_back(callee);
        reverseCallGraph[callee].push_back(caller);
    }

    // Helper lambdas using reverse call graph
    auto callsTarget = [&](uint64_t addr, uint64_t target) -> bool {
        auto it = callGraph.find(addr);
        if (it == callGraph.end()) return false;
        for (uint64_t c : it->second) if (c == target) return true;
        return false;
    };
    auto callsAny = [&](uint64_t addr, const std::set<uint64_t>& targets) -> bool {
        auto it = callGraph.find(addr);
        if (it == callGraph.end()) return false;
        for (uint64_t c : it->second) if (targets.count(c)) return true;
        return false;
    };
    auto countCalls = [&](uint64_t addr, const std::set<uint64_t>& targets) -> int {
        auto it = callGraph.find(addr);
        if (it == callGraph.end()) return 0;
        int cnt = 0;
        for (uint64_t c : it->second) if (targets.count(c)) ++cnt;
        return cnt;
    };

    // Step 2: Find known addresses from symbol table + function names
    uint64_t entryAddr = 0;
    uint64_t mainAddr = 0;
    std::set<uint64_t> inittermThunks;
    std::set<uint64_t> setAppTypeThunks;
    std::set<uint64_t> securityTimeThunks;
    bool hasGuiImports = false;

    SymbolIterator symIt = symTable->getAllProgramSymbols(true);
    while (symIt.hasNext()) {
        Symbol* sym = symIt.next();
        if (!sym) continue;
        std::string n = sym->getName();
        uint64_t a = sym->getAddress().getOffset();
        if (a == 0) continue;
        if (n == "entry") entryAddr = a;
        if (n == "main") mainAddr = a;
        if (n == "thunk_RegisterClassW" || n == "thunk_RegisterClassA" ||
            n == "thunk_CreateWindowExW" || n == "thunk_CreateWindowExA" ||
            n == "thunk_ShowWindow" || n == "thunk_DialogBoxParamW" ||
            n == "thunk_DefWindowProcW" || n == "thunk_DispatchMessageW" ||
            n == "thunk_TranslateMessage" || n == "thunk_GetMessageW" ||
            n == "DelayLoad_RegisterClassW" || n == "DelayLoad_RegisterClassA" ||
            n == "DelayLoad_CreateWindowExW" || n == "DelayLoad_CreateWindowExA" ||
            n == "DelayLoad_ShowWindow" || n == "DelayLoad_DialogBoxParamW" ||
            n == "DelayLoad_DefWindowProcW" || n == "DelayLoad_DispatchMessageW" ||
            n == "DelayLoad_TranslateMessage" || n == "DelayLoad_GetMessageW" ||
            n == "DelayLoad_ShellExecuteW") hasGuiImports = true;
        if (n.rfind("thunk__initterm", 0) == 0)
            inittermThunks.insert(a);
        if (n.rfind("thunk__set_app_type", 0) == 0)
            setAppTypeThunks.insert(a);
        if (n == "thunk_GetSystemTimeAsFileTime" || n == "thunk_QueryPerformanceCounter" ||
            n == "thunk_GetCurrentProcessId" || n == "thunk_GetCurrentThreadId")
            securityTimeThunks.insert(a);
    }

    // Also scan function names for thunks (uses cached allFunctions)
    for (Function* f : allFunctions) {
        std::string n = f->getName();
        uint64_t a = f->getEntryPoint().getOffset();
        if (a == 0) continue;
        if (n == "entry") entryAddr = a;
        if (n == "main") mainAddr = a;
        if (n.rfind("thunk__initterm", 0) == 0 && !inittermThunks.count(a))
            inittermThunks.insert(a);
        if (n.rfind("thunk__set_app_type", 0) == 0 && !setAppTypeThunks.count(a))
            setAppTypeThunks.insert(a);
    }

    // Step 3: Name the entry function
    if (entryAddr > 0) {
        for (Function* f : allFunctions) {
            if (f->getEntryPoint().getOffset() != entryAddr) continue;
            std::string cn = f->getName();
            if (cn.rfind("FUN_", 0) == 0 || cn.rfind("sub_", 0) == 0 ||
                cn.rfind("func_start_", 0) == 0) {
                std::string startupName = hasGuiImports ? "WinMainCRTStartup" : "mainCRTStartup";
                if (tryRename(entryAddr, startupName)) ++identified;
            }
        }
    }

    uint64_t sehAddr = 0;

    // Step 4: Find __scrt_common_main_seh
    {
        for (Function* f : allFunctions) {
            uint64_t a = f->getEntryPoint().getOffset();
            if (a == entryAddr || a == mainAddr) continue;
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            bool callsInit = countCalls(a, inittermThunks) >= 1;
            bool callsApp = countCalls(a, setAppTypeThunks) >= 1;
            if (callsInit || callsApp) {
                if (tryRename(a, "__scrt_common_main_seh")) {
                    ++identified;
                    sehAddr = a;
                    break;
                }
            }
        }

        // Step 5: Find invoke_main — called from __scrt_common_main_seh, calls main
        if (sehAddr > 0) {
            uint64_t invAddr = 0;
            auto sehIt = callGraph.find(sehAddr);
            if (sehIt != callGraph.end()) {
                for (uint64_t sehCallee : sehIt->second) {
                    if (sehCallee == entryAddr || sehCallee == sehAddr) continue;
                    if (mainAddr > 0 && callsTarget(sehCallee, mainAddr)) {
                        if (tryRename(sehCallee, "invoke_main")) {
                            ++identified; invAddr = sehCallee; break;
                        }
                    }
                }
            }
            if (invAddr == 0 && mainAddr > 0) {
                for (Function* f : allFunctions) {
                    uint64_t a = f->getEntryPoint().getOffset();
                    if (a == entryAddr || a == mainAddr) continue;
                    std::string cn = f->getName();
                    if (!NamingService::isAutoGeneratedName(cn)) continue;
                    if (callsTarget(a, mainAddr)) {
                        if (tryRename(a, "invoke_main")) {
                            ++identified; break;
                        }
                    }
                }
            }
        }
    }

    // Step 5 (duplicate): Search all functions that call main
    if (mainAddr > 0) {
        for (Function* f : allFunctions) {
            uint64_t a = f->getEntryPoint().getOffset();
            if (a == entryAddr || a == mainAddr) continue;
            if (callsTarget(a, mainAddr)) {
                std::string cn = f->getName();
                if (NamingService::isAutoGeneratedName(cn)) {
                    if (tryRename(a, "invoke_main")) { ++identified; break; }
                }
            }
        }
    }

    // Step 6: __security_init_cookie
    if (!securityTimeThunks.empty()) {
        for (Function* f : allFunctions) {
            uint64_t a = f->getEntryPoint().getOffset();
            if (a == entryAddr || a == mainAddr) continue;
            if (callsAny(a, securityTimeThunks)) {
                std::string cn = f->getName();
                if (NamingService::isAutoGeneratedName(cn)) {
                    if (tryRename(a, "__security_init_cookie")) ++identified;
                }
            }
        }
    }

    // Step 7: __security_check_cookie
    {
        for (Function* f : allFunctions) {
            uint64_t a = f->getEntryPoint().getOffset();
            if (a == entryAddr || a == mainAddr) continue;
            uint64_t nCallers = static_cast<uint64_t>(reverseCallGraph[a].size());
            if (nCallers < 5) continue;

            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            MemoryBlock* block = memory ? memory->getBlock(f->getEntryPoint()) : nullptr;
            if (!block || !block->isInitialized() || !block->isExecute()) continue;

            uint8_t buf[16];
            int r = block->getBytes(f->getEntryPoint(), buf, 16);
            if (r < 8) continue;

            bool hasCookie = false;
            for (int i = 0; i <= r - 3; ++i) {
                if ((buf[i] == 0x48 && buf[i+1] == 0x33 && buf[i+2] == 0x0D) ||
                    (buf[i] == 0x48 && buf[i+1] == 0x3B && buf[i+2] == 0x0D)) {
                    hasCookie = true; break;
                }
            }
            if (hasCookie && tryRename(a, "__security_check_cookie")) ++identified;
        }
    }

    // Step 8: _guard_check_icall and _guard_dispatch_icall
    {
        for (Function* f : allFunctions) {
            uint64_t a = f->getEntryPoint().getOffset();
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            MemoryBlock* block = memory ? memory->getBlock(f->getEntryPoint()) : nullptr;
            if (!block || !block->isInitialized() || !block->isExecute()) continue;

            uint8_t buf[8];
            int r = block->getBytes(f->getEntryPoint(), buf, 8);
            if (r < 3) continue;

            if (r >= 3 && buf[0] == 0xC2 && buf[1] == 0x00 && buf[2] == 0x00) {
                if (tryRename(a, "_guard_check_icall")) ++identified;
                continue;
            }

            if (r >= 2 && buf[0] == 0xFF && buf[1] == 0xE0) {
                if (tryRename(a, "_guard_dispatch_icall")) ++identified;
                continue;
            }
        }
    }

    // Step 9: Collect FKS candidates for functions with named callers.
    // No renaming here — all FKS-based renaming is deferred to Step 11
    // which applies full neighbor-context ranking.
    if (fksAvailable) {
        for (Function* f : allFunctions) {
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            uint64_t a = f->getEntryPoint().getOffset();

            // Skip if already has pending candidates from Step 0
            if (pendingFksCandidates.count(a)) continue;

            // Check if any caller of this function is already named
            bool hasNamedCaller = false;
            auto callersIt = reverseCallGraph.find(a);
            if (callersIt != reverseCallGraph.end()) {
                for (uint64_t caller : callersIt->second) {
                    Function* callerFunc = funcMgr->getFunctionAt(
                        Address(defaultSpace, static_cast<int64_t>(caller)));
                    if (callerFunc && !NamingService::isAutoGeneratedName(callerFunc->getName())) {
                        hasNamedCaller = true;
                        break;
                    }
                }
            }
            if (!hasNamedCaller) continue;

            FunctionFingerprint fp = fingerprinter.compute(f, program);
            if (fp.v2.fullHash == 0 && fp.v1.fullHash == 0) continue;

            auto candidates = collectFksCandidates(fp, f);
            if (!candidates.empty()) {
                pendingFksCandidates[a] = std::move(candidates);
            }
        }
    }

    // Step 10: Call Graph Fingerprints — propagate names by callee-set similarity.
    // Build a local index: callee-set hash → named function. For each unnamed
    // function with the same callee set as a named one, propagate the name.
    // This catches functions that share structural call patterns but differ in
    // byte-level hashes (e.g., different compilation units, inlined variants).
    {
        // Build index: hash of sorted callee addresses → named function name
        // Only consider functions that are already named (from prior steps).
        struct CalleeSetKey {
            std::vector<uint64_t> callees;
            bool operator==(const CalleeSetKey& o) const { return callees == o.callees; }
        };
        struct CalleeSetHash {
            size_t operator()(const CalleeSetKey& k) const {
                size_t h = 0;
                for (uint64_t c : k.callees) {
                    h ^= std::hash<uint64_t>{}(c) + 0x9e3779b9 + (h << 6) + (h >> 2);
                }
                return h;
            }
        };

        // Map from callee-set hash to best (most-specific) name seen
        std::unordered_map<size_t, std::string> calleeSetIndex;
        // Map from callee-set hash to the set of callees (for exact matching)
        std::unordered_map<size_t, std::vector<uint64_t>> calleeSetData;

        for (Function* f : allFunctions) {
            std::string cn = f->getName();
            if (NamingService::isAutoGeneratedName(cn)) continue;

            uint64_t a = f->getEntryPoint().getOffset();
            auto cgIt = callGraph.find(a);
            if (cgIt == callGraph.end() || cgIt->second.empty()) continue;

            // Sort callees for consistent hashing
            std::vector<uint64_t> sorted = cgIt->second;
            std::sort(sorted.begin(), sorted.end());

            CalleeSetKey key{sorted};
            size_t hash = CalleeSetHash{}(key);

            // Only store the first name seen (don't overwrite with less-specific names)
            if (!calleeSetIndex.count(hash)) {
                calleeSetIndex[hash] = cn;
                calleeSetData[hash] = sorted;
            }
        }

        // Propagate: for each unnamed function, compute its callee-set hash
        // and look up in the index. Require exact callee-set match (not just hash).
        int propagated = 0;
        for (Function* f : allFunctions) {
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            uint64_t a = f->getEntryPoint().getOffset();
            auto cgIt = callGraph.find(a);
            if (cgIt == callGraph.end() || cgIt->second.empty()) continue;

            std::vector<uint64_t> sorted = cgIt->second;
            std::sort(sorted.begin(), sorted.end());

            CalleeSetKey key{sorted};
            size_t hash = CalleeSetHash{}(key);

            auto idxIt = calleeSetIndex.find(hash);
            if (idxIt == calleeSetIndex.end()) continue;

            // Verify exact match (avoid hash collisions)
            if (calleeSetData[hash] != sorted) continue;

            // Don't propagate from auto-generated names
            const std::string& donorName = idxIt->second;
            if (NamingService::isAutoGeneratedName(donorName)) continue;

            if (tryRename(a, donorName)) ++propagated;
        }

        if (propagated > 0) {
            Msg::info("FidAnalyzer",
                      "Call Graph Fingerprints: propagated " +
                      std::to_string(propagated) + " names via callee-set matching");
            identified += propagated;
        }
    }

    // Step 11: Neighbor Context Matching — disambiguate multiple FKS candidates
    // using the local call graph. When a hash lookup returns multiple candidates
    // from different libraries, score each by comparing its known callee UIDs
    // (from FksRelation tables) against the local binary's callees that have
    // already been identified. The candidate with the most overlapping callees
    // is the best match.
    if (fksAvailable) {
        // Build callee index: UID → sorted callee UIDs (from all .fkslib files)
        auto calleeIndex = storage::FksIndexManager::buildCalleeIndex(fksDir);

        // Build reverse mapping: for each local function already identified,
        // map its address → FKS UID via address-based lookup (O(1) per function,
        // no fingerprinting needed).
        std::unordered_map<uint64_t, uint64_t> localAddrToFksUid;
        if (!familyName.empty()) {
            for (Function* f : allFunctions) {
                std::string cn = f->getName();
                if (NamingService::isAutoGeneratedName(cn)) continue;

                uint64_t a = f->getEntryPoint().getOffset();
                auto data = storage::FksIndexManager::lookupByAddress(fksDir, familyName, a);
                auto candidates = storage::FksIndexManager::extractAllCandidates(data);
                if (!candidates.empty()) {
                    localAddrToFksUid[a] = candidates[0].uid;
                }
            }
        }

        int contextRenamed = 0;

        // Process pending candidates from Steps 0 and 9 (deferred FKS lookups).
        // These were collected during hash-only passes; now apply full neighbor-context
        // scoring and ranking before renaming.
        for (auto& [addr, allCandidates] : pendingFksCandidates) {
            Function* f = funcMgr->getFunctionAt(
                Address(defaultSpace, static_cast<int64_t>(addr)));
            if (!f) continue;
            if (!NamingService::isAutoGeneratedName(f->getName())) continue;

            // Single candidate: direct rename (no disambiguation needed)
            if (allCandidates.size() == 1) {
                if (!NamingService::isAutoGeneratedName(allCandidates[0].name)) {
                    if (tryRename(addr, allCandidates[0].name)) ++contextRenamed;
                }
                continue;
            }

            // Multiple candidates: build local callee UID set
            std::vector<uint64_t> localCalleeUids;
            auto cgIt = callGraph.find(addr);
            if (cgIt != callGraph.end()) {
                for (uint64_t calleeAddr : cgIt->second) {
                    auto uidIt = localAddrToFksUid.find(calleeAddr);
                    if (uidIt != localAddrToFksUid.end()) {
                        localCalleeUids.push_back(uidIt->second);
                    }
                }
                std::sort(localCalleeUids.begin(), localCalleeUids.end());
            }

            // Score each candidate by callee overlap
            const storage::CandidateInfo* bestCandidate = nullptr;
            int bestScore = -1;

            for (auto& cand : allCandidates) {
                if (NamingService::isAutoGeneratedName(cand.name)) continue;

                int score = storage::FksIndexManager::scoreCandidateByCallees(
                    cand, calleeIndex, localCalleeUids);

                if (score == bestScore && bestCandidate) {
                    if (cand.family == familyName && bestCandidate->family != familyName) {
                        bestCandidate = &cand;
                    }
                } else if (score > bestScore) {
                    bestScore = score;
                    bestCandidate = &cand;
                }
            }

            if (bestCandidate && bestScore >= 0) {
                if (tryRename(addr, bestCandidate->name)) ++contextRenamed;
            }
        }

        // For remaining unnamed functions (not in pendingFksCandidates), do hash
        // lookups and apply same scoring logic.
        for (Function* f : allFunctions) {
            std::string cn = f->getName();
            if (!NamingService::isAutoGeneratedName(cn)) continue;

            uint64_t a = f->getEntryPoint().getOffset();

            // Skip if already processed via pendingCandidates
            if (pendingFksCandidates.count(a)) continue;

            FunctionFingerprint fp = fingerprinter.compute(f, program);
            if (fp.v2.fullHash == 0 && fp.v1.fullHash == 0) continue;

            // Collect ALL candidates from the best hash match
            std::vector<storage::CandidateInfo> allCandidates;

            if (fp.v2.shortHash != 0) {
                auto data = storage::FksIndexManager::lookupByShortHashV2(fksDir, fp.v2.shortHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }
            if (allCandidates.empty() && fp.v2.fullHash != 0 && fp.v2.fullHash != fp.v2.shortHash) {
                auto data = storage::FksIndexManager::lookupByFullHashV2(fksDir, fp.v2.fullHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }
            if (allCandidates.empty() && fp.v2.mnemHash != 0) {
                auto data = storage::FksIndexManager::lookupByMnemHashV2(fksDir, fp.v2.mnemHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }
            if (allCandidates.empty() && fp.v2.callHash != 0) {
                auto data = storage::FksIndexManager::lookupByCallHashV2(fksDir, fp.v2.callHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }

            if (allCandidates.empty() && fp.v1.fullHash != 0) {
                auto data = storage::FksIndexManager::lookupByFullHash(fksDir, fp.v1.fullHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }
            if (allCandidates.empty() && fp.v1.shortHash != 0 && fp.v1.shortHash != fp.v1.fullHash) {
                auto data = storage::FksIndexManager::lookupByShortHash(fksDir, fp.v1.shortHash);
                auto cands = storage::FksIndexManager::extractAllCandidates(data);
                allCandidates.insert(allCandidates.end(), cands.begin(), cands.end());
            }
            if (allCandidates.empty()) continue;

            if (allCandidates.size() == 1) {
                if (!NamingService::isAutoGeneratedName(allCandidates[0].name)) {
                    if (tryRename(a, allCandidates[0].name)) ++contextRenamed;
                }
                continue;
            }

            std::vector<uint64_t> localCalleeUids;
            auto cgIt = callGraph.find(a);
            if (cgIt != callGraph.end()) {
                for (uint64_t calleeAddr : cgIt->second) {
                    auto uidIt = localAddrToFksUid.find(calleeAddr);
                    if (uidIt != localAddrToFksUid.end()) {
                        localCalleeUids.push_back(uidIt->second);
                    }
                }
                std::sort(localCalleeUids.begin(), localCalleeUids.end());
            }

            const storage::CandidateInfo* bestCandidate = nullptr;
            int bestScore = -1;

            for (auto& cand : allCandidates) {
                if (NamingService::isAutoGeneratedName(cand.name)) continue;

                int score = storage::FksIndexManager::scoreCandidateByCallees(
                    cand, calleeIndex, localCalleeUids);

                if (score == bestScore && bestCandidate) {
                    if (cand.family == familyName && bestCandidate->family != familyName) {
                        bestCandidate = &cand;
                    }
                } else if (score > bestScore) {
                    bestScore = score;
                    bestCandidate = &cand;
                }
            }

            if (bestCandidate && bestScore >= 0) {
                if (tryRename(a, bestCandidate->name)) ++contextRenamed;
            }
        }

        if (contextRenamed > 0) {
            Msg::info("FidAnalyzer",
                      "Neighbor Context: disambiguated " +
                      std::to_string(contextRenamed) + " functions via callee-set scoring");
            identified += contextRenamed;
        }
    }

    if (identified > 0)
        Msg::info(getName(), "Identified " + std::to_string(identified) +
                  " CRT/library functions via call-chain analysis.");
    return true;
}

} // namespace ghidra
