#include <ghidra/NamingService.h>
#include <ghidra/Program.h>
#include <ghidra/FunctionManager.h>
#include <ghidra/Function.h>
#include <ghidra/FunctionIterator.h>
#include <ghidra/SymbolTable.h>
#include <ghidra/Symbol.h>
#include <ghidra/SymbolUtilities.h>
#include <ghidra/Msg.h>
#include <ghidra/Address.h>
#include <ghidra/AddressSpace.h>
#include <sstream>

namespace ghidra {

// ── Auto-generated name patterns ──────────────────────────────────────────

bool NamingService::isAutoGeneratedName(const std::string& name) {
    return SymbolUtilities::isAutoGeneratedName(name);
}

// ── Constructor ───────────────────────────────────────────────────────────

NamingService::NamingService(Program* program)
    : program_(program) {}

FunctionManager* NamingService::getFuncMgr() const {
    return program_ ? program_->getFunctionManager() : nullptr;
}

SymbolTable* NamingService::getSymTable() const {
    return program_ ? program_->getSymbolTable() : nullptr;
}

// ── Address resolution helper ─────────────────────────────────────────────

static Address addrFromOffset(Program* program, uint64_t offset) {
    if (!program) return Address();
    const AddressSpace* space = program->getAddressFactory()->getDefaultAddressSpace();
    if (!space) return Address();
    return Address(const_cast<AddressSpace*>(space), static_cast<int64_t>(offset));
}

// ── canRename: checks if a rename is allowed by priority ─────────────────

bool NamingService::canRename(const Function* func, SourceType newSource) const {
    if (!func) return false;
    SourceType current = func->getSource();
    if (current == SourceType::DEFAULT) return true;
    return isHigherOrEqualPriorityThan(newSource, current);
}

bool NamingService::canRename(const Symbol* sym, SourceType newSource) const {
    if (!sym) return false;
    SourceType current = sym->getSource();
    if (current == SourceType::DEFAULT) return true;
    return isHigherOrEqualPriorityThan(newSource, current);
}

bool NamingService::canRename(uint64_t addr, SourceType newSource) const {
    FunctionManager* fm = getFuncMgr();
    if (fm) {
        Function* func = fm->getFunctionAt(addrFromOffset(program_, addr));
        if (func) return canRename(func, newSource);
    }
    SymbolTable* st = getSymTable();
    if (st) {
        Symbol* sym = st->getPrimarySymbol(addrFromOffset(program_, addr));
        if (sym) return canRename(sym, newSource);
    }
    return true;
}

// ── assignName: Function ─────────────────────────────────────────────────

NamingService::RenameResult NamingService::assignName(
    Function* func, const std::string& newName, SourceType source) {
    RenameResult result;
    if (!func || newName.empty()) {
        result.reason = "null function or empty name";
        return result;
    }

    result.oldName = func->getName();
    result.address = func->getEntryPoint().getOffset();

    SourceType current = func->getSource();

    if (current != SourceType::DEFAULT &&
        isLowerPriorityThan(source, current)) {
        result.blocked = true;
        result.reason = "source " + sourceTypeToString(source) +
                        " cannot overwrite " + sourceTypeToString(current);
        logRename(result.address, result.oldName, newName, "",
                  source, true, result.reason);
        return result;
    }

    func->setName(newName);
    func->setSource(source);

    logRename(result.address, result.oldName, newName, "", source, false, "");
    result.success = true;
    return result;
}

// ── assignName: Symbol ───────────────────────────────────────────────────

NamingService::RenameResult NamingService::assignName(
    Symbol* sym, const std::string& newName, SourceType source) {
    RenameResult result;
    if (!sym || newName.empty()) {
        result.reason = "null symbol or empty name";
        return result;
    }

    result.oldName = sym->getName();
    result.address = sym->getAddress().getOffset();

    SourceType current = sym->getSource();

    if (current != SourceType::DEFAULT &&
        isLowerPriorityThan(source, current)) {
        result.blocked = true;
        result.reason = "source " + sourceTypeToString(source) +
                        " cannot overwrite " + sourceTypeToString(current);
        logRename(result.address, result.oldName, newName, "",
                  source, true, result.reason);
        return result;
    }

    sym->setName(newName);
    sym->setSource(source);

    logRename(result.address, result.oldName, newName, "", source, false, "");
    result.success = true;
    return result;
}

// ── assignName: by address ───────────────────────────────────────────────

NamingService::RenameResult NamingService::assignName(
    uint64_t addr, const std::string& newName, SourceType source) {
    RenameResult result;
    Address address = addrFromOffset(program_, addr);
    if (!address.isValid()) {
        result.reason = "invalid address";
        return result;
    }

    FunctionManager* fm = getFuncMgr();
    if (fm) {
        Function* func = fm->getFunctionAt(address);
        if (func) return assignName(func, newName, source);
    }

    SymbolTable* st = getSymTable();
    if (st) {
        Symbol* sym = st->getPrimarySymbol(address);
        if (sym) return assignName(sym, newName, source);
    }

    assignAlias(addr, newName, source);
    result.success = true;
    return result;
}

// ── assignAlias ──────────────────────────────────────────────────────────

void NamingService::assignAlias(
    uint64_t addr, const std::string& aliasName, SourceType source) {
    SymbolTable* st = getSymTable();
    if (!st) return;
    Address address = addrFromOffset(program_, addr);
    if (!address.isValid()) return;
    st->createLabel(address, aliasName, source);
}

// ── Audit logging ────────────────────────────────────────────────────────

void NamingService::logRename(
    uint64_t addr, const std::string& oldName, const std::string& newName,
    const std::string& analyzer, SourceType source,
    bool blocked, const std::string& reason) {
    AuditEntry entry;
    entry.address = addr;
    entry.oldName = oldName;
    entry.newName = newName;
    entry.analyzerName = analyzer;
    entry.source = source;
    entry.blocked = blocked;
    entry.blockReason = reason;
    auditLog_.push_back(std::move(entry));
}

// ── Audit summary and report ─────────────────────────────────────────────

NamingService::AuditSummary NamingService::getAuditSummary() const {
    AuditSummary summary;
    for (const auto& e : auditLog_) {
        if (e.blocked) {
            summary.blockedRenames++;
            continue;
        }
        summary.totalRenames++;
        if (e.analyzerName.find("Fid") != std::string::npos ||
            e.analyzerName.find("Function ID") != std::string::npos)
            summary.byFid++;
        else if (e.analyzerName.find("Main") != std::string::npos)
            summary.byMainRecognition++;
        else if (e.analyzerName.find("Demangle") != std::string::npos ||
                 e.analyzerName.find("GNU") != std::string::npos ||
                 e.analyzerName.find("Microsoft") != std::string::npos ||
                 e.analyzerName.find("Rust") != std::string::npos ||
                 e.analyzerName.find("Swift") != std::string::npos)
            summary.byDemangler++;
        else if (e.analyzerName.find("Import") != std::string::npos)
            summary.byImporter++;
        else if (e.source == SourceType::USER_DEFINED ||
                 e.source == SourceType::USER_DEFINED_ADD)
            summary.byUserDefined++;
        else
            summary.byAnalyzer++;
    }
    return summary;
}

std::string NamingService::generateAuditReport() const {
    std::ostringstream ss;
    ss << "=== Naming Service Audit Report ===\n\n";

    AuditSummary sum = getAuditSummary();
    ss << "Total renames applied:  " << sum.totalRenames << "\n";
    ss << "Total renames blocked:  " << sum.blockedRenames << "\n\n";

    ss << "By analyzer:\n";
    ss << "  FidAnalyzer:            " << sum.byFid << "\n";
    ss << "  MainRecognition:        " << sum.byMainRecognition << "\n";
    ss << "  Demanglers:             " << sum.byDemangler << "\n";
    ss << "  ImportThunk:            " << sum.byImporter << "\n";
    ss << "  Other analyzers:        " << sum.byAnalyzer << "\n";
    ss << "  User-defined:           " << sum.byUserDefined << "\n\n";

    if (!auditLog_.empty()) {
        ss << "--- Rename Log ---\n";
        for (const auto& e : auditLog_) {
            ss << "  0x" << std::hex << e.address << std::dec
               << " '" << e.oldName << "' -> '" << e.newName << "'"
               << " [" << sourceTypeToString(e.source) << "]"
               << (e.blocked ? " BLOCKED: " + e.blockReason : "")
               << "\n";
        }
    }

    return ss.str();
}

} // namespace ghidra
