#include <ghidra/TypeDatabase.h>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <memory>
#include <algorithm>
#include <cctype>

namespace ghidra {
namespace {

struct PrototypeEntry {
    const char* returnType;
    std::vector<const char*> paramTypes;
};

const std::unordered_map<std::string, PrototypeEntry>& getTypeTable() {
    static const std::unordered_map<std::string, PrototypeEntry> table = {
        // ===== Kernel32 =====
        {"GetLastError",              {"DWORD", {}}},
        {"SetLastError",              {"void", {"DWORD"}}},
        {"GetModuleHandleA",          {"HMODULE", {"LPCSTR"}}},
        {"GetModuleHandleW",          {"HMODULE", {"LPCWSTR"}}},
        {"GetProcAddress",            {"FARPROC", {"HMODULE", "LPCSTR"}}},
        {"LoadLibraryA",              {"HMODULE", {"LPCSTR"}}},
        {"LoadLibraryW",              {"HMODULE", {"LPCWSTR"}}},
        {"LoadLibraryExA",            {"HMODULE", {"LPCSTR", "HANDLE", "DWORD"}}},
        {"LoadLibraryExW",            {"HMODULE", {"LPCWSTR", "HANDLE", "DWORD"}}},
        {"FreeLibrary",               {"BOOL", {"HMODULE"}}},
        {"FreeLibraryAndExitThread",  {"void", {"HMODULE", "DWORD"}}},
        {"DisableThreadLibraryCalls", {"BOOL", {"HMODULE"}}},
        {"VirtualProtect",            {"BOOL", {"LPVOID", "SIZE_T", "DWORD", "PDWORD"}}},
        {"VirtualAlloc",              {"LPVOID", {"LPVOID", "SIZE_T", "DWORD", "DWORD"}}},
        {"VirtualFree",               {"BOOL", {"LPVOID", "SIZE_T", "DWORD"}}},
        {"VirtualQuery",              {"SIZE_T", {"LPCVOID", "PMEMORY_BASIC_INFORMATION", "SIZE_T"}}},
        {"VirtualAllocEx",            {"LPVOID", {"HANDLE", "LPVOID", "SIZE_T", "DWORD", "DWORD"}}},
        {"VirtualFreeEx",             {"BOOL", {"HANDLE", "LPVOID", "SIZE_T", "DWORD"}}},
        {"VirtualProtectEx",          {"BOOL", {"HANDLE", "LPVOID", "SIZE_T", "DWORD", "PDWORD"}}},
        {"HeapAlloc",                 {"LPVOID", {"HANDLE", "DWORD", "SIZE_T"}}},
        {"HeapFree",                  {"BOOL", {"HANDLE", "DWORD", "LPVOID"}}},
        {"HeapReAlloc",               {"LPVOID", {"HANDLE", "DWORD", "LPVOID", "SIZE_T"}}},
        {"HeapSize",                  {"SIZE_T", {"HANDLE", "DWORD", "LPCVOID"}}},
        {"GetProcessHeap",            {"HANDLE", {}}},
        {"CreateFileA",               {"HANDLE", {"LPCSTR", "DWORD", "DWORD", "LPSECURITY_ATTRIBUTES", "DWORD", "DWORD", "HANDLE"}}},
        {"CreateFileW",               {"HANDLE", {"LPCWSTR", "DWORD", "DWORD", "LPSECURITY_ATTRIBUTES", "DWORD", "DWORD", "HANDLE"}}},
        {"ReadFile",                  {"BOOL", {"HANDLE", "LPVOID", "DWORD", "LPDWORD", "LPOVERLAPPED"}}},
        {"WriteFile",                 {"BOOL", {"HANDLE", "LPCVOID", "DWORD", "LPDWORD", "LPOVERLAPPED"}}},
        {"CloseHandle",               {"BOOL", {"HANDLE"}}},
        {"GetFileSize",               {"DWORD", {"HANDLE", "LPDWORD"}}},
        {"GetFileSizeEx",             {"BOOL", {"HANDLE", "PLARGE_INTEGER"}}},
        {"SetFilePointer",            {"DWORD", {"HANDLE", "LONG", "PLONG", "DWORD"}}},
        {"SetFilePointerEx",          {"BOOL", {"HANDLE", "LARGE_INTEGER", "PLARGE_INTEGER", "DWORD"}}},
        {"SetEndOfFile",              {"BOOL", {"HANDLE"}}},
        {"FlushFileBuffers",          {"BOOL", {"HANDLE"}}},
        {"GetStdHandle",              {"HANDLE", {"DWORD"}}},
        {"CreateToolhelp32Snapshot",  {"HANDLE", {"DWORD", "DWORD"}}},
        {"Process32FirstW",           {"BOOL", {"HANDLE", "LPPROCESSENTRY32W"}}},
        {"Process32NextW",            {"BOOL", {"HANDLE", "LPPROCESSENTRY32W"}}},
        {"Module32FirstW",            {"BOOL", {"HANDLE", "LPMODULEENTRY32W"}}},
        {"Module32NextW",             {"BOOL", {"HANDLE", "LPMODULEENTRY32W"}}},
        {"Thread32First",             {"BOOL", {"HANDLE", "LPTHREADENTRY32"}}},
        {"Thread32Next",              {"BOOL", {"HANDLE", "LPTHREADENTRY32"}}},
        {"CreateProcessA",            {"BOOL", {"LPCSTR", "LPSTR", "LPSECURITY_ATTRIBUTES", "LPSECURITY_ATTRIBUTES", "BOOL", "DWORD", "LPVOID", "LPCSTR", "LPSTARTUPINFOA", "LPPROCESS_INFORMATION"}}},
        {"CreateProcessW",            {"BOOL", {"LPCWSTR", "LPWSTR", "LPSECURITY_ATTRIBUTES", "LPSECURITY_ATTRIBUTES", "BOOL", "DWORD", "LPVOID", "LPCWSTR", "LPSTARTUPINFOW", "LPPROCESS_INFORMATION"}}},
        {"WaitForSingleObject",       {"DWORD", {"HANDLE", "DWORD"}}},
        {"WaitForMultipleObjects",    {"DWORD", {"DWORD", "const HANDLE*", "BOOL", "DWORD"}}},
        {"GetExitCodeProcess",        {"BOOL", {"HANDLE", "LPDWORD"}}},
        {"ExitProcess",               {"void", {"UINT"}}},
        {"TerminateProcess",          {"BOOL", {"HANDLE", "UINT"}}},
        {"GetCurrentProcess",         {"HANDLE", {}}},
        {"GetCurrentProcessId",       {"DWORD", {}}},
        {"GetCurrentThread",          {"HANDLE", {}}},
        {"GetCurrentThreadId",        {"DWORD", {}}},
        {"OpenProcess",               {"HANDLE", {"DWORD", "BOOL", "DWORD"}}},
        {"CreateThread",              {"HANDLE", {"LPSECURITY_ATTRIBUTES", "SIZE_T", "LPTHREAD_START_ROUTINE", "LPVOID", "DWORD", "LPDWORD"}}},
        {"CreateRemoteThread",        {"HANDLE", {"HANDLE", "LPSECURITY_ATTRIBUTES", "SIZE_T", "LPTHREAD_START_ROUTINE", "LPVOID", "DWORD", "LPDWORD"}}},
        {"ExitThread",                {"void", {"DWORD"}}},
        {"GetExitCodeThread",         {"BOOL", {"HANDLE", "LPDWORD"}}},
        {"Sleep",                     {"void", {"DWORD"}}},
        {"SleepEx",                   {"DWORD", {"DWORD", "BOOL"}}},
        {"GetSystemTime",             {"void", {"LPSYSTEMTIME"}}},
        {"GetLocalTime",              {"void", {"LPSYSTEMTIME"}}},
        {"SetSystemTime",             {"BOOL", {"const SYSTEMTIME*"}}},
        {"GetTickCount",              {"DWORD", {}}},
        {"GetTickCount64",            {"ULONGLONG", {}}},
        {"QueryPerformanceCounter",   {"BOOL", {"LARGE_INTEGER*"}}},
        {"QueryPerformanceFrequency", {"BOOL", {"LARGE_INTEGER*"}}},
        {"GetComputerNameA",          {"BOOL", {"LPSTR", "LPDWORD"}}},
        {"GetComputerNameW",          {"BOOL", {"LPWSTR", "LPDWORD"}}},
        {"GetUserNameA",              {"BOOL", {"LPSTR", "LPDWORD"}}},
        {"GetUserNameW",              {"BOOL", {"LPWSTR", "LPDWORD"}}},
        {"GetCommandLineA",           {"LPSTR", {}}},
        {"GetCommandLineW",           {"LPWSTR", {}}},
        {"GetEnvironmentVariableA",   {"DWORD", {"LPCSTR", "LPSTR", "DWORD"}}},
        {"GetEnvironmentVariableW",   {"DWORD", {"LPCWSTR", "LPWSTR", "DWORD"}}},
        {"SetEnvironmentVariableA",   {"BOOL", {"LPCSTR", "LPCSTR"}}},
        {"SetEnvironmentVariableW",   {"BOOL", {"LPCWSTR", "LPCWSTR"}}},
        {"GetModuleFileNameA",        {"DWORD", {"HMODULE", "LPSTR", "DWORD"}}},
        {"GetModuleFileNameW",        {"DWORD", {"HMODULE", "LPWSTR", "DWORD"}}},
        {"GetSystemDirectoryA",       {"UINT", {"LPSTR", "UINT"}}},
        {"GetSystemDirectoryW",       {"UINT", {"LPWSTR", "UINT"}}},
        {"GetWindowsDirectoryA",      {"UINT", {"LPSTR", "UINT"}}},
        {"GetWindowsDirectoryW",      {"UINT", {"LPWSTR", "UINT"}}},
        {"ExpandEnvironmentStringsA", {"DWORD", {"LPCSTR", "LPSTR", "DWORD"}}},
        {"ExpandEnvironmentStringsW", {"DWORD", {"LPCWSTR", "LPWSTR", "DWORD"}}},
        {"FormatMessageA",            {"DWORD", {"DWORD", "LPCVOID", "DWORD", "DWORD", "LPSTR", "DWORD", "va_list*"}}},
        {"FormatMessageW",            {"DWORD", {"DWORD", "LPCVOID", "DWORD", "DWORD", "LPWSTR", "DWORD", "va_list*"}}},
        {"LocalFree",                 {"HLOCAL", {"HLOCAL"}}},
        {"GlobalFree",                {"HGLOBAL", {"HGLOBAL"}}},
        {"lstrlenA",                  {"int", {"LPCSTR"}}},
        {"lstrlenW",                  {"int", {"LPCWSTR"}}},
        {"lstrcmpA",                  {"int", {"LPCSTR", "LPCSTR"}}},
        {"lstrcmpW",                  {"int", {"LPCWSTR", "LPCWSTR"}}},
        {"lstrcpyA",                  {"LPSTR", {"LPSTR", "LPCSTR"}}},
        {"lstrcpyW",                  {"LPWSTR", {"LPWSTR", "LPCWSTR"}}},
        {"lstrcatA",                  {"LPSTR", {"LPSTR", "LPCSTR"}}},
        {"lstrcatW",                  {"LPWSTR", {"LPWSTR", "LPCWSTR"}}},
        {"LoadResource",              {"HGLOBAL", {"HMODULE", "HRSRC"}}},
        {"LockResource",              {"LPVOID", {"HGLOBAL"}}},
        {"SizeofResource",            {"DWORD", {"HMODULE", "HRSRC"}}},
        {"FindResourceA",             {"HRSRC", {"HMODULE", "LPCSTR", "LPCSTR"}}},
        {"FindResourceW",             {"HRSRC", {"HMODULE", "LPCWSTR", "LPCWSTR"}}},
        {"DeleteFileA",               {"BOOL", {"LPCSTR"}}},
        {"DeleteFileW",               {"BOOL", {"LPCWSTR"}}},
        {"MoveFileA",                 {"BOOL", {"LPCSTR", "LPCSTR"}}},
        {"MoveFileW",                 {"BOOL", {"LPCWSTR", "LPCWSTR"}}},
        {"MoveFileExA",               {"BOOL", {"LPCSTR", "LPCSTR", "DWORD"}}},
        {"MoveFileExW",               {"BOOL", {"LPCWSTR", "LPCWSTR", "DWORD"}}},
        {"CopyFileA",                 {"BOOL", {"LPCSTR", "LPCSTR", "BOOL"}}},
        {"CopyFileW",                 {"BOOL", {"LPCWSTR", "LPCWSTR", "BOOL"}}},
        {"CreateDirectoryA",          {"BOOL", {"LPCSTR", "LPSECURITY_ATTRIBUTES"}}},
        {"CreateDirectoryW",          {"BOOL", {"LPCWSTR", "LPSECURITY_ATTRIBUTES"}}},
        {"RemoveDirectoryA",          {"BOOL", {"LPCSTR"}}},
        {"RemoveDirectoryW",          {"BOOL", {"LPCWSTR"}}},
        {"FindFirstFileA",            {"HANDLE", {"LPCSTR", "LPWIN32_FIND_DATAA"}}},
        {"FindFirstFileW",            {"HANDLE", {"LPCWSTR", "LPWIN32_FIND_DATAW"}}},
        {"FindNextFileA",             {"BOOL", {"HANDLE", "LPWIN32_FIND_DATAA"}}},
        {"FindNextFileW",             {"BOOL", {"HANDLE", "LPWIN32_FIND_DATAW"}}},
        {"FindClose",                 {"BOOL", {"HANDLE"}}},
        {"SetCurrentDirectoryA",      {"BOOL", {"LPCSTR"}}},
        {"SetCurrentDirectoryW",      {"BOOL", {"LPCWSTR"}}},
        {"GetCurrentDirectoryA",      {"DWORD", {"DWORD", "LPSTR"}}},
        {"GetCurrentDirectoryW",      {"DWORD", {"DWORD", "LPWSTR"}}},
        {"GetFullPathNameA",          {"DWORD", {"LPCSTR", "DWORD", "LPSTR", "LPSTR*"}}},
        {"GetFullPathNameW",          {"DWORD", {"LPCWSTR", "DWORD", "LPWSTR", "LPWSTR*"}}},
        {"GetFileAttributesA",        {"DWORD", {"LPCSTR"}}},
        {"GetFileAttributesW",        {"DWORD", {"LPCWSTR"}}},
        {"SetFileAttributesA",        {"BOOL", {"LPCSTR", "DWORD"}}},
        {"SetFileAttributesW",        {"BOOL", {"LPCWSTR", "DWORD"}}},
        {"GetTempPathA",              {"DWORD", {"DWORD", "LPSTR"}}},
        {"GetTempPathW",              {"DWORD", {"DWORD", "LPWSTR"}}},
        {"GetTempFileNameA",          {"UINT", {"LPCSTR", "LPCSTR", "UINT", "LPSTR"}}},
        {"GetTempFileNameW",          {"UINT", {"LPCWSTR", "LPCWSTR", "UINT", "LPWSTR"}}},
        {"CreateEventA",              {"HANDLE", {"LPSECURITY_ATTRIBUTES", "BOOL", "BOOL", "LPCSTR"}}},
        {"CreateEventW",              {"HANDLE", {"LPSECURITY_ATTRIBUTES", "BOOL", "BOOL", "LPCWSTR"}}},
        {"CreateMutexA",              {"HANDLE", {"LPSECURITY_ATTRIBUTES", "BOOL", "LPCSTR"}}},
        {"CreateMutexW",              {"HANDLE", {"LPSECURITY_ATTRIBUTES", "BOOL", "LPCWSTR"}}},
        {"OpenEventA",                {"HANDLE", {"DWORD", "BOOL", "LPCSTR"}}},
        {"OpenEventW",                {"HANDLE", {"DWORD", "BOOL", "LPCWSTR"}}},
        {"OpenMutexA",                {"HANDLE", {"DWORD", "BOOL", "LPCSTR"}}},
        {"OpenMutexW",                {"HANDLE", {"DWORD", "BOOL", "LPCWSTR"}}},
        {"CreateSemaphoreA",          {"HANDLE", {"LPSECURITY_ATTRIBUTES", "LONG", "LONG", "LPCSTR"}}},
        {"CreateSemaphoreW",          {"HANDLE", {"LPSECURITY_ATTRIBUTES", "LONG", "LONG", "LPCWSTR"}}},
        {"OpenSemaphoreA",            {"HANDLE", {"DWORD", "BOOL", "LPCSTR"}}},
        {"OpenSemaphoreW",            {"HANDLE", {"DWORD", "BOOL", "LPCWSTR"}}},
        {"SetEvent",                  {"BOOL", {"HANDLE"}}},
        {"ResetEvent",                {"BOOL", {"HANDLE"}}},
        {"ReleaseMutex",              {"BOOL", {"HANDLE"}}},
        {"ReleaseSemaphore",          {"BOOL", {"HANDLE", "LONG", "LPLONG"}}},
        {"Beep",                      {"BOOL", {"DWORD", "DWORD"}}},
        {"GetOEMCP",                  {"UINT", {}}},
        {"GetACP",                    {"UINT", {}}},
        {"MultiByteToWideChar",       {"int", {"UINT", "DWORD", "LPCSTR", "int", "LPWSTR", "int"}}},
        {"WideCharToMultiByte",       {"int", {"UINT", "DWORD", "LPCWSTR", "int", "LPSTR", "int", "LPCSTR", "LPBOOL"}}},
        {"IsDebuggerPresent",         {"BOOL", {}}},
        {"DebugBreak",                {"void", {}}},
        {"OutputDebugStringA",        {"void", {"LPCSTR"}}},
        {"OutputDebugStringW",        {"void", {"LPCWSTR"}}},
        {"RaiseException",            {"void", {"DWORD", "DWORD", "DWORD", "const ULONG_PTR*"}}},
        {"GetExceptionCode",          {"DWORD", {}}},
        {"UnhandledExceptionFilter",  {"LONG", {"LPEXCEPTION_POINTERS"}}},
        {"SetUnhandledExceptionFilter",{"LPTOP_LEVEL_EXCEPTION_FILTER", {"LPTOP_LEVEL_EXCEPTION_FILTER"}}},
        {"ReadProcessMemory",         {"BOOL", {"HANDLE", "LPCVOID", "LPVOID", "SIZE_T", "SIZE_T*"}}},
        {"WriteProcessMemory",        {"BOOL", {"HANDLE", "LPVOID", "LPCVOID", "SIZE_T", "SIZE_T*"}}},
        {"FlsAlloc",                  {"DWORD", {"PFLS_CALLBACK_FUNCTION"}}},
        {"FlsGetValue",               {"PVOID", {"DWORD"}}},
        {"FlsSetValue",               {"BOOL", {"DWORD", "PVOID"}}},
        {"FlsFree",                   {"BOOL", {"DWORD"}}},
        {"TlsAlloc",                  {"DWORD", {}}},
        {"TlsGetValue",               {"LPVOID", {"DWORD"}}},
        {"TlsSetValue",               {"BOOL", {"DWORD", "LPVOID"}}},
        {"TlsFree",                   {"BOOL", {"DWORD"}}},
        {"InitializeCriticalSection", {"void", {"LPCRITICAL_SECTION"}}},
        {"EnterCriticalSection",      {"void", {"LPCRITICAL_SECTION"}}},
        {"LeaveCriticalSection",      {"void", {"LPCRITICAL_SECTION"}}},
        {"DeleteCriticalSection",     {"void", {"LPCRITICAL_SECTION"}}},
        {"InitializeCriticalSectionAndSpinCount", {"BOOL", {"LPCRITICAL_SECTION", "DWORD"}}},
        {"TryEnterCriticalSection",   {"BOOL", {"LPCRITICAL_SECTION"}}},
        {"InterlockedIncrement",      {"LONG", {"LPLONG"}}},
        {"InterlockedDecrement",      {"LONG", {"LPLONG"}}},
        {"InterlockedExchange",       {"LONG", {"LPLONG", "LONG"}}},
        {"InterlockedExchangeAdd",    {"LONG", {"LPLONG", "LONG"}}},
        {"InterlockedCompareExchange",{"LONG", {"LPLONG", "LONG", "LONG"}}},
        {"InitializeSListHead",       {"void", {"PSLIST_HEADER"}}},
        {"InterlockedPopEntrySList",  {"PSLIST_ENTRY", {"PSLIST_HEADER"}}},
        {"InterlockedPushEntrySList", {"PSLIST_ENTRY", {"PSLIST_HEADER", "PSLIST_ENTRY"}}},
        {"GetStartupInfoA",           {"void", {"LPSTARTUPINFOA"}}},
        {"GetStartupInfoW",           {"void", {"LPSTARTUPINFOW"}}},

        // ===== User32 =====
        {"MessageBoxA",               {"int", {"HWND", "LPCSTR", "LPCSTR", "UINT"}}},
        {"MessageBoxW",               {"int", {"HWND", "LPCWSTR", "LPCWSTR", "UINT"}}},
        {"MessageBoxExA",             {"int", {"HWND", "LPCSTR", "LPCSTR", "UINT", "WORD"}}},
        {"MessageBoxExW",             {"int", {"HWND", "LPCWSTR", "LPCWSTR", "UINT", "WORD"}}},
        {"GetMessageA",               {"BOOL", {"LPMSG", "HWND", "UINT", "UINT"}}},
        {"GetMessageW",               {"BOOL", {"LPMSG", "HWND", "UINT", "UINT"}}},
        {"PeekMessageA",              {"BOOL", {"LPMSG", "HWND", "UINT", "UINT", "UINT"}}},
        {"PeekMessageW",              {"BOOL", {"LPMSG", "HWND", "UINT", "UINT", "UINT"}}},
        {"GetWindowTextA",            {"int", {"HWND", "LPSTR", "int"}}},
        {"GetWindowTextW",            {"int", {"HWND", "LPWSTR", "int"}}},
        {"GetWindowTextLengthA",      {"int", {"HWND"}}},
        {"GetWindowTextLengthW",      {"int", {"HWND"}}},
        {"SetWindowTextA",            {"BOOL", {"HWND", "LPCSTR"}}},
        {"SetWindowTextW",            {"BOOL", {"HWND", "LPCWSTR"}}},
        {"FindWindowA",               {"HWND", {"LPCSTR", "LPCSTR"}}},
        {"FindWindowW",               {"HWND", {"LPCWSTR", "LPCWSTR"}}},
        {"FindWindowExA",             {"HWND", {"HWND", "HWND", "LPCSTR", "LPCSTR"}}},
        {"FindWindowExW",             {"HWND", {"HWND", "HWND", "LPCWSTR", "LPCWSTR"}}},
        {"GetDesktopWindow",          {"HWND", {}}},
        {"GetForegroundWindow",       {"HWND", {}}},
        {"GetTopWindow",              {"HWND", {"HWND"}}},
        {"GetWindow",                 {"HWND", {"HWND", "UINT"}}},
        {"GetParent",                 {"HWND", {"HWND"}}},
        {"SetParent",                 {"HWND", {"HWND", "HWND"}}},
        {"ShowWindow",                {"BOOL", {"HWND", "int"}}},
        {"IsWindowVisible",           {"BOOL", {"HWND"}}},
        {"IsWindowEnabled",           {"BOOL", {"HWND"}}},
        {"EnableWindow",              {"BOOL", {"HWND", "BOOL"}}},
        {"DestroyWindow",             {"BOOL", {"HWND"}}},
        {"CreateWindowExA",           {"HWND", {"DWORD", "LPCSTR", "LPCSTR", "DWORD", "int", "int", "int", "int", "HWND", "HMENU", "HINSTANCE", "LPVOID"}}},
        {"CreateWindowExW",           {"HWND", {"DWORD", "LPCWSTR", "LPCWSTR", "DWORD", "int", "int", "int", "int", "HWND", "HMENU", "HINSTANCE", "LPVOID"}}},
        {"DispatchMessageA",          {"LRESULT", {"const MSG*"}}},
        {"DispatchMessageW",          {"LRESULT", {"const MSG*"}}},
        {"TranslateMessage",          {"BOOL", {"const MSG*"}}},
        {"PostMessageA",              {"BOOL", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"PostMessageW",              {"BOOL", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"PostQuitMessage",           {"void", {"int"}}},
        {"SendMessageA",              {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"SendMessageW",              {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"SendMessageTimeoutA",       {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM", "UINT", "UINT", "PDWORD_PTR"}}},
        {"SendMessageTimeoutW",       {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM", "UINT", "UINT", "PDWORD_PTR"}}},
        {"RegisterClassA",            {"ATOM", {"const WNDCLASSA*"}}},
        {"RegisterClassW",            {"ATOM", {"const WNDCLASSW*"}}},
        {"RegisterClassExA",          {"ATOM", {"const WNDCLASSEXA*"}}},
        {"RegisterClassExW",          {"ATOM", {"const WNDCLASSEXW*"}}},
        {"DefWindowProcA",            {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"DefWindowProcW",            {"LRESULT", {"HWND", "UINT", "WPARAM", "LPARAM"}}},
        {"GetClassInfoA",             {"BOOL", {"HINSTANCE", "LPCSTR", "LPWNDCLASSA"}}},
        {"GetClassInfoW",             {"BOOL", {"HINSTANCE", "LPCWSTR", "LPWNDCLASSW"}}},
        {"BeginPaint",                {"HDC", {"HWND", "LPPAINTSTRUCT"}}},
        {"EndPaint",                  {"BOOL", {"HWND", "const PAINTSTRUCT*"}}},
        {"GetDC",                     {"HDC", {"HWND"}}},
        {"ReleaseDC",                 {"int", {"HWND", "HDC"}}},
        {"UpdateWindow",              {"BOOL", {"HWND"}}},
        {"InvalidateRect",            {"BOOL", {"HWND", "const RECT*", "BOOL"}}},
        {"LoadCursorA",               {"HCURSOR", {"HINSTANCE", "LPCSTR"}}},
        {"LoadCursorW",               {"HCURSOR", {"HINSTANCE", "LPCWSTR"}}},
        {"LoadIconA",                 {"HICON", {"HINSTANCE", "LPCSTR"}}},
        {"LoadIconW",                 {"HICON", {"HINSTANCE", "LPCWSTR"}}},
        {"LoadImageA",                {"HANDLE", {"HINSTANCE", "LPCSTR", "UINT", "int", "int", "UINT"}}},
        {"LoadImageW",                {"HANDLE", {"HINSTANCE", "LPCWSTR", "UINT", "int", "int", "UINT"}}},
        {"GetSystemMetrics",          {"int", {"int"}}},
        {"GetClientRect",             {"BOOL", {"HWND", "LPRECT"}}},
        {"GetWindowRect",             {"BOOL", {"HWND", "LPRECT"}}},
        {"AdjustWindowRect",          {"BOOL", {"LPRECT", "DWORD", "BOOL"}}},
        {"MoveWindow",                {"BOOL", {"HWND", "int", "int", "int", "int", "BOOL"}}},
        {"SetWindowPos",              {"BOOL", {"HWND", "HWND", "int", "int", "int", "int", "UINT"}}},
        {"GetDlgItem",                {"HWND", {"HWND", "int"}}},
        {"GetDlgItemTextA",           {"UINT", {"HWND", "int", "LPSTR", "int"}}},
        {"GetDlgItemTextW",           {"UINT", {"HWND", "int", "LPWSTR", "int"}}},
        {"SetDlgItemTextA",           {"BOOL", {"HWND", "int", "LPCSTR"}}},
        {"SetDlgItemTextW",           {"BOOL", {"HWND", "int", "LPCWSTR"}}},
        {"CharLowerA",                {"LPSTR", {"LPSTR"}}},
        {"CharLowerW",                {"LPWSTR", {"LPWSTR"}}},
        {"CharUpperA",                {"LPSTR", {"LPSTR"}}},
        {"CharUpperW",                {"LPWSTR", {"LPWSTR"}}},
        {"wsprintfA",                 {"int", {"LPSTR", "LPCSTR"}}},
        {"wsprintfW",                 {"int", {"LPWSTR", "LPCWSTR"}}},
        {"IsCharAlphaA",              {"BOOL", {"CHAR"}}},
        {"IsCharAlphaNumericA",       {"BOOL", {"CHAR"}}},
        {"IsCharUpperA",              {"BOOL", {"CHAR"}}},
        {"IsCharLowerA",              {"BOOL", {"CHAR"}}},

        // ===== Advapi32 =====
        {"RegOpenKeyExA",             {"LONG", {"HKEY", "LPCSTR", "DWORD", "REGSAM", "PHKEY"}}},
        {"RegOpenKeyExW",             {"LONG", {"HKEY", "LPCWSTR", "DWORD", "REGSAM", "PHKEY"}}},
        {"RegCreateKeyExA",           {"LONG", {"HKEY", "LPCSTR", "DWORD", "LPSTR", "DWORD", "REGSAM", "LPSECURITY_ATTRIBUTES", "PHKEY", "LPDWORD"}}},
        {"RegCreateKeyExW",           {"LONG", {"HKEY", "LPCWSTR", "DWORD", "LPWSTR", "DWORD", "REGSAM", "LPSECURITY_ATTRIBUTES", "PHKEY", "LPDWORD"}}},
        {"RegCloseKey",               {"LONG", {"HKEY"}}},
        {"RegQueryValueExA",          {"LONG", {"HKEY", "LPCSTR", "LPDWORD", "LPDWORD", "LPBYTE", "LPDWORD"}}},
        {"RegQueryValueExW",          {"LONG", {"HKEY", "LPCWSTR", "LPDWORD", "LPDWORD", "LPBYTE", "LPDWORD"}}},
        {"RegSetValueExA",            {"LONG", {"HKEY", "LPCSTR", "DWORD", "DWORD", "const BYTE*", "DWORD"}}},
        {"RegSetValueExW",            {"LONG", {"HKEY", "LPCWSTR", "DWORD", "DWORD", "const BYTE*", "DWORD"}}},
        {"RegDeleteKeyA",             {"LONG", {"HKEY", "LPCSTR"}}},
        {"RegDeleteKeyW",             {"LONG", {"HKEY", "LPCWSTR"}}},
        {"RegEnumKeyExA",             {"LONG", {"HKEY", "DWORD", "LPSTR", "LPDWORD", "LPDWORD", "LPSTR", "LPDWORD", "PFILETIME"}}},
        {"RegEnumKeyExW",             {"LONG", {"HKEY", "DWORD", "LPWSTR", "LPDWORD", "LPDWORD", "LPWSTR", "LPDWORD", "PFILETIME"}}},
        {"RegEnumValueA",             {"LONG", {"HKEY", "DWORD", "LPSTR", "LPDWORD", "LPDWORD", "LPDWORD", "LPBYTE", "LPDWORD"}}},
        {"RegEnumValueW",             {"LONG", {"HKEY", "DWORD", "LPWSTR", "LPDWORD", "LPDWORD", "LPDWORD", "LPBYTE", "LPDWORD"}}},
        {"RegDeleteValueA",           {"LONG", {"HKEY", "LPCSTR"}}},
        {"RegDeleteValueW",           {"LONG", {"HKEY", "LPCWSTR"}}},
        {"OpenSCManagerA",            {"SC_HANDLE", {"LPCSTR", "LPCSTR", "DWORD"}}},
        {"OpenSCManagerW",            {"SC_HANDLE", {"LPCWSTR", "LPCWSTR", "DWORD"}}},
        {"OpenServiceA",              {"SC_HANDLE", {"SC_HANDLE", "LPCSTR", "DWORD"}}},
        {"OpenServiceW",              {"SC_HANDLE", {"SC_HANDLE", "LPCWSTR", "DWORD"}}},
        {"StartServiceA",             {"BOOL", {"SC_HANDLE", "DWORD", "const LPCSTR*"}}},
        {"StartServiceW",             {"BOOL", {"SC_HANDLE", "DWORD", "const LPCWSTR*"}}},
        {"ControlService",            {"BOOL", {"SC_HANDLE", "DWORD", "LPSERVICE_STATUS"}}},
        {"CloseServiceHandle",        {"BOOL", {"SC_HANDLE"}}},
        {"QueryServiceStatus",        {"BOOL", {"SC_HANDLE", "LPSERVICE_STATUS"}}},
        {"CryptAcquireContextA",      {"BOOL", {"HCRYPTPROV*", "LPCSTR", "LPCSTR", "DWORD", "DWORD"}}},
        {"CryptAcquireContextW",      {"BOOL", {"HCRYPTPROV*", "LPCWSTR", "LPCWSTR", "DWORD", "DWORD"}}},
        {"CryptReleaseContext",       {"BOOL", {"HCRYPTPROV", "DWORD"}}},
        {"CryptGenRandom",            {"BOOL", {"HCRYPTPROV", "DWORD", "BYTE*"}}},
        {"CryptCreateHash",           {"BOOL", {"HCRYPTPROV", "ALG_ID", "HCRYPTKEY", "DWORD", "HCRYPTHASH*"}}},
        {"CryptHashData",             {"BOOL", {"HCRYPTHASH", "const BYTE*", "DWORD", "DWORD"}}},
        {"CryptDeriveKey",            {"BOOL", {"HCRYPTPROV", "ALG_ID", "HCRYPTHASH", "DWORD", "HCRYPTKEY*"}}},
        {"CryptEncrypt",              {"BOOL", {"HCRYPTKEY", "HCRYPTHASH", "BOOL", "DWORD", "BYTE*", "DWORD*", "DWORD"}}},
        {"CryptDecrypt",              {"BOOL", {"HCRYPTKEY", "HCRYPTHASH", "BOOL", "DWORD", "BYTE*", "DWORD*"}}},
        {"CryptDestroyKey",           {"BOOL", {"HCRYPTKEY"}}},
        {"CryptDestroyHash",          {"BOOL", {"HCRYPTHASH"}}},
        {"LogonUserA",                {"BOOL", {"LPCSTR", "LPCSTR", "LPCSTR", "DWORD", "DWORD", "PHANDLE"}}},
        {"LogonUserW",                {"BOOL", {"LPCWSTR", "LPCWSTR", "LPCWSTR", "DWORD", "DWORD", "PHANDLE"}}},

        // ===== WS2_32 =====
        {"WSAStartup",                {"int", {"WORD", "LPWSADATA"}}},
        {"WSACleanup",                {"int", {}}},
        {"socket",                    {"SOCKET", {"int", "int", "int"}}},
        {"bind",                      {"int", {"SOCKET", "const sockaddr*", "int"}}},
        {"listen",                    {"int", {"SOCKET", "int"}}},
        {"accept",                    {"SOCKET", {"SOCKET", "sockaddr*", "int*"}}},
        {"connect",                   {"int", {"SOCKET", "const sockaddr*", "int"}}},
        {"recv",                      {"int", {"SOCKET", "char*", "int", "int"}}},
        {"send",                      {"int", {"SOCKET", "const char*", "int", "int"}}},
        {"sendto",                    {"int", {"SOCKET", "const char*", "int", "int", "const sockaddr*", "int"}}},
        {"recvfrom",                  {"int", {"SOCKET", "char*", "int", "int", "sockaddr*", "int*"}}},
        {"closesocket",               {"int", {"SOCKET"}}},
        {"shutdown",                  {"int", {"SOCKET", "int"}}},
        {"setsockopt",                {"int", {"SOCKET", "int", "int", "const char*", "int"}}},
        {"getsockopt",                {"int", {"SOCKET", "int", "int", "char*", "int*"}}},
        {"gethostbyname",             {"struct hostent*", {"const char*"}}},
        {"getpeername",               {"int", {"SOCKET", "sockaddr*", "int*"}}},
        {"getsockname",               {"int", {"SOCKET", "sockaddr*", "int*"}}},
        {"select",                    {"int", {"int", "fd_set*", "fd_set*", "fd_set*", "const timeval*"}}},
        {"ioctlsocket",               {"int", {"SOCKET", "long", "u_long*"}}},
        {"WSAGetLastError",           {"int", {}}},
        {"htonl",                     {"u_long", {"u_long"}}},
        {"htons",                     {"u_short", {"u_short"}}},
        {"ntohl",                     {"u_long", {"u_long"}}},
        {"ntohs",                     {"u_short", {"u_short"}}},
        {"inet_addr",                 {"unsigned long", {"const char*"}}},
        {"inet_ntoa",                 {"char*", {"struct in_addr"}}},
        {"gethostname",               {"int", {"char*", "int"}}},

        // ===== GDI32 =====
        {"TextOutA",                  {"BOOL", {"HDC", "int", "int", "LPCSTR", "int"}}},
        {"TextOutW",                  {"BOOL", {"HDC", "int", "int", "LPCWSTR", "int"}}},
        {"GetStockObject",            {"HGDIOBJ", {"int"}}},
        {"GetTextExtentPoint32A",     {"BOOL", {"HDC", "LPCSTR", "int", "LPSIZE"}}},
        {"GetTextExtentPoint32W",     {"BOOL", {"HDC", "LPCWSTR", "int", "LPSIZE"}}},
        {"SelectObject",              {"HGDIOBJ", {"HDC", "HGDIOBJ"}}},
        {"DeleteObject",              {"BOOL", {"HGDIOBJ"}}},
        {"DeleteDC",                  {"BOOL", {"HDC"}}},
        {"CreateCompatibleDC",        {"HDC", {"HDC"}}},
        {"CreateCompatibleBitmap",    {"HBITMAP", {"HDC", "int", "int"}}},
        {"BitBlt",                    {"BOOL", {"HDC", "int", "int", "int", "int", "HDC", "int", "int", "DWORD"}}},
        {"StretchBlt",                {"BOOL", {"HDC", "int", "int", "int", "int", "HDC", "int", "int", "int", "int", "DWORD"}}},
        {"SetBkColor",                {"COLORREF", {"HDC", "COLORREF"}}},
        {"SetTextColor",              {"COLORREF", {"HDC", "COLORREF"}}},
        {"GetDeviceCaps",             {"int", {"HDC", "int"}}},
        {"Rectangle",                 {"BOOL", {"HDC", "int", "int", "int", "int"}}},
        {"Ellipse",                   {"BOOL", {"HDC", "int", "int", "int", "int"}}},
        {"LineTo",                    {"BOOL", {"HDC", "int", "int"}}},
        {"MoveToEx",                  {"BOOL", {"HDC", "int", "int", "LPPOINT"}}},
        {"GetPixel",                  {"COLORREF", {"HDC", "int", "int"}}},
        {"SetPixel",                  {"COLORREF", {"HDC", "int", "int", "COLORREF"}}},
        {"CreateSolidBrush",          {"HBRUSH", {"COLORREF"}}},
        {"CreateFontA",               {"HFONT", {"int", "int", "int", "int", "int", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "LPCSTR"}}},
        {"CreateFontW",               {"HFONT", {"int", "int", "int", "int", "int", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "DWORD", "LPCWSTR"}}},
        {"GetTextMetricsA",           {"BOOL", {"HDC", "LPTEXTMETRICA"}}},
        {"GetTextMetricsW",           {"BOOL", {"HDC", "LPTEXTMETRICW"}}},
        {"SetBkMode",                 {"int", {"HDC", "int"}}},
        {"PatBlt",                    {"BOOL", {"HDC", "int", "int", "int", "int", "DWORD"}}},
        {"GetUpdateRect",             {"BOOL", {"HWND", "LPRECT", "BOOL"}}},
        {"DrawTextA",                 {"int", {"HDC", "LPCSTR", "int", "LPRECT", "UINT"}}},
        {"DrawTextW",                 {"int", {"HDC", "LPCWSTR", "int", "LPRECT", "UINT"}}},

        // ===== Shell32 =====
        {"ShellExecuteA",             {"HINSTANCE", {"HWND", "LPCSTR", "LPCSTR", "LPCSTR", "LPCSTR", "int"}}},
        {"ShellExecuteW",             {"HINSTANCE", {"HWND", "LPCWSTR", "LPCWSTR", "LPCWSTR", "LPCWSTR", "int"}}},
        {"SHGetFileInfoA",            {"DWORD_PTR", {"LPCSTR", "DWORD", "SHFILEINFOA*", "UINT", "UINT"}}},
        {"SHGetFileInfoW",            {"DWORD_PTR", {"LPCWSTR", "DWORD", "SHFILEINFOW*", "UINT", "UINT"}}},
        {"SHGetPathFromIDListA",      {"BOOL", {"LPCITEMIDLIST", "LPSTR"}}},
        {"SHGetPathFromIDListW",      {"BOOL", {"LPCITEMIDLIST", "LPWSTR"}}},
        {"SHBrowseForFolderA",        {"LPITEMIDLIST", {"LPBROWSEINFOA"}}},
        {"SHBrowseForFolderW",        {"LPITEMIDLIST", {"LPBROWSEINFOW"}}},
        {"SHGetFolderPathA",          {"HRESULT", {"HWND", "int", "HANDLE", "DWORD", "LPSTR"}}},
        {"SHGetFolderPathW",          {"HRESULT", {"HWND", "int", "HANDLE", "DWORD", "LPWSTR"}}},
        {"SHGetKnownFolderPath",      {"HRESULT", {"REFKNOWNFOLDERID", "DWORD", "HANDLE", "PWSTR*"}}},
        {"PathFindFileNameA",         {"LPCSTR", {"LPCSTR"}}},
        {"PathFindFileNameW",         {"LPCWSTR", {"LPCWSTR"}}},
        {"PathRemoveFileSpecA",       {"BOOL", {"LPSTR"}}},
        {"PathRemoveFileSpecW",       {"BOOL", {"LPWSTR"}}},
        {"PathCombineA",              {"LPSTR", {"LPSTR", "LPCSTR", "LPCSTR"}}},
        {"PathCombineW",              {"LPWSTR", {"LPWSTR", "LPCWSTR", "LPCWSTR"}}},
        {"PathFindExtensionA",        {"LPCSTR", {"LPCSTR"}}},
        {"PathFindExtensionW",        {"LPCWSTR", {"LPCWSTR"}}},
        {"PathIsDirectoryA",          {"BOOL", {"LPCSTR"}}},
        {"PathIsDirectoryW",          {"BOOL", {"LPCWSTR"}}},
        {"PathFileExistsA",           {"BOOL", {"LPCSTR"}}},
        {"PathFileExistsW",           {"BOOL", {"LPCWSTR"}}},

        // ===== Comctl32 =====
        {"InitCommonControls",        {"void", {}}},
        {"InitCommonControlsEx",      {"BOOL", {"LPINITCOMMONCONTROLSEX"}}},
        {"ImageList_Create",          {"HIMAGELIST", {"int", "int", "UINT", "int", "int"}}},
        {"ImageList_Destroy",         {"BOOL", {"HIMAGELIST"}}},
        {"ImageList_Add",             {"int", {"HIMAGELIST", "HBITMAP", "HBITMAP"}}},
        {"ImageList_Remove",          {"BOOL", {"HIMAGELIST", "int"}}},
        {"ImageList_GetImageCount",   {"int", {"HIMAGELIST"}}},
        {"ImageList_GetImageInfo",    {"BOOL", {"HIMAGELIST", "int", "IMAGEINFO*"}}},
        {"ImageList_Draw",            {"BOOL", {"HIMAGELIST", "int", "HDC", "int", "int", "UINT"}}},
        {"ImageList_ReplaceIcon",     {"int", {"HIMAGELIST", "int", "HICON"}}},

        // ===== NTDLL =====
        {"RtlMoveMemory",             {"void", {"void*", "const void*", "SIZE_T"}}},
        {"RtlCopyMemory",             {"void", {"void*", "const void*", "SIZE_T"}}},
        {"RtlFillMemory",             {"void", {"void*", "SIZE_T", "BYTE"}}},
        {"RtlZeroMemory",             {"void", {"void*", "SIZE_T"}}},
        {"RtlCompareMemory",          {"SIZE_T", {"const void*", "const void*", "SIZE_T"}}},
        {"RtlAllocateHeap",           {"PVOID", {"PVOID", "ULONG", "SIZE_T"}}},
        {"RtlFreeHeap",               {"BOOLEAN", {"PVOID", "ULONG", "PVOID"}}},
        {"RtlReAllocateHeap",         {"PVOID", {"PVOID", "ULONG", "PVOID", "SIZE_T"}}},
        {"RtlCreateHeap",             {"PVOID", {"ULONG", "PVOID", "SIZE_T", "SIZE_T", "PVOID", "ULONG"}}},
        {"RtlDestroyHeap",            {"BOOLEAN", {"PVOID"}}},
        {"NtQueryInformationProcess", {"NTSTATUS", {"HANDLE", "PROCESSINFOCLASS", "PVOID", "ULONG", "PULONG"}}},
        {"NtQuerySystemInformation",  {"NTSTATUS", {"SYSTEM_INFORMATION_CLASS", "PVOID", "ULONG", "PULONG"}}},
        {"NtCreateFile",              {"NTSTATUS", {"PHANDLE", "ACCESS_MASK", "POBJECT_ATTRIBUTES", "PIO_STATUS_BLOCK", "PLARGE_INTEGER", "ULONG", "ULONG", "ULONG", "ULONG", "PVOID", "ULONG"}}},
        {"NtClose",                   {"NTSTATUS", {"HANDLE"}}},
        {"NtDeviceIoControlFile",     {"NTSTATUS", {"HANDLE", "HANDLE", "PIO_APC_ROUTINE", "PVOID", "PIO_STATUS_BLOCK", "ULONG", "PVOID", "ULONG", "PVOID", "ULONG"}}},

        // ===== Bcrypt =====
        {"BCryptOpenAlgorithmProvider",{"NTSTATUS", {"BCRYPT_ALG_HANDLE*", "LPCWSTR", "LPCWSTR", "ULONG"}}},
        {"BCryptCloseAlgorithmProvider",{"NTSTATUS", {"BCRYPT_ALG_HANDLE", "ULONG"}}},
        {"BCryptGenerateSymmetricKey", {"NTSTATUS", {"BCRYPT_ALG_HANDLE", "BCRYPT_KEY_HANDLE*", "PUCHAR", "ULONG", "PUCHAR", "ULONG", "ULONG"}}},
        {"BCryptEncrypt",             {"NTSTATUS", {"BCRYPT_KEY_HANDLE", "PUCHAR", "ULONG", "PVOID", "PUCHAR", "ULONG", "PUCHAR", "ULONG", "ULONG*", "ULONG"}}},
        {"BCryptDecrypt",             {"NTSTATUS", {"BCRYPT_KEY_HANDLE", "PUCHAR", "ULONG", "PVOID", "PUCHAR", "ULONG", "PUCHAR", "ULONG", "ULONG*", "ULONG"}}},
        {"BCryptHashData",            {"NTSTATUS", {"BCRYPT_HASH_HANDLE", "PUCHAR", "ULONG", "ULONG"}}},
        {"BCryptFinishHash",          {"NTSTATUS", {"BCRYPT_HASH_HANDLE", "PUCHAR", "ULONG", "ULONG"}}},
        {"BCryptCreateHash",          {"NTSTATUS", {"BCRYPT_ALG_HANDLE", "BCRYPT_HASH_HANDLE*", "PUCHAR", "ULONG", "PUCHAR", "ULONG", "ULONG"}}},
        {"BCryptDestroyHash",         {"NTSTATUS", {"BCRYPT_HASH_HANDLE"}}},
        {"BCryptDestroyKey",          {"NTSTATUS", {"BCRYPT_KEY_HANDLE"}}},
        {"BCryptSetProperty",         {"NTSTATUS", {"BCRYPT_HANDLE", "LPCWSTR", "PUCHAR", "ULONG", "ULONG"}}},
        {"BCryptGetProperty",         {"NTSTATUS", {"BCRYPT_HANDLE", "LPCWSTR", "PUCHAR", "ULONG", "ULONG*", "ULONG"}}},

        // ===== No-return C runtime =====
        {"abort",                     {"void", {}}},
        {"exit",                      {"void", {"int"}}},
        {"_exit",                     {"void", {"int"}}},
        {"quick_exit",                {"void", {"int"}}},
        {"_cexit",                    {"void", {}}},
        {"_c_exit",                   {"void", {}}},
        {"longjmp",                   {"void", {"jmp_buf", "int"}}},

        // ===== Standard C (also common) =====
        {"printf",                    {"int", {"const char*"}}},
        {"__mingw_printf",            {"int", {"const char*"}}},
        {"__mingw_fprintf",           {"int", {"FILE*", "const char*"}}},
        {"__mingw_sprintf",           {"int", {"char*", "const char*"}}},
        {"__mingw_snprintf",          {"int", {"char*", "size_t", "const char*"}}},
        {"__mingw_vfprintf",          {"int", {"FILE*", "const char*", "va_list"}}},
        {"__mingw_vsprintf",          {"int", {"char*", "const char*", "va_list"}}},
        {"__mingw_vsnprintf",         {"int", {"char*", "size_t", "const char*", "va_list"}}},
        {"sprintf",                   {"int", {"char*", "const char*"}}},
        {"snprintf",                  {"int", {"char*", "size_t", "const char*"}}},
        {"fprintf",                   {"int", {"FILE*", "const char*"}}},
        {"puts",                      {"int", {"const char*"}}},
        {"fputs",                     {"int", {"const char*", "FILE*"}}},
        {"fgets",                     {"char*", {"char*", "int", "FILE*"}}},
        {"scanf",                     {"int", {"const char*"}}},
        {"__mingw_scanf",             {"int", {"const char*"}}},
        {"__mingw_fscanf",            {"int", {"FILE*", "const char*"}}},
        {"__mingw_sscanf",            {"int", {"const char*", "const char*"}}},
        {"sscanf",                    {"int", {"const char*", "const char*"}}},
        {"fscanf",                    {"int", {"FILE*", "const char*"}}},
        {"fopen",                     {"FILE*", {"const char*", "const char*"}}},
        {"fclose",                    {"int", {"FILE*"}}},
        {"fread",                     {"size_t", {"void*", "size_t", "size_t", "FILE*"}}},
        {"fwrite",                    {"size_t", {"const void*", "size_t", "size_t", "FILE*"}}},
        {"malloc",                    {"void*", {"size_t"}}},
        {"calloc",                    {"void*", {"size_t", "size_t"}}},
        {"realloc",                   {"void*", {"void*", "size_t"}}},
        {"free",                      {"void", {"void*"}}},
        {"memcpy",                    {"void*", {"void*", "const void*", "size_t"}}},
        {"memmove",                   {"void*", {"void*", "const void*", "size_t"}}},
        {"memset",                    {"void*", {"void*", "int", "size_t"}}},
        {"memcmp",                    {"int", {"const void*", "const void*", "size_t"}}},
        {"strlen",                    {"size_t", {"const char*"}}},
        {"strcmp",                    {"int", {"const char*", "const char*"}}},
        {"strncmp",                   {"int", {"const char*", "const char*", "size_t"}}},
        {"strcpy",                    {"char*", {"char*", "const char*"}}},
        {"strncpy",                   {"char*", {"char*", "const char*", "size_t"}}},
        {"strcat",                    {"char*", {"char*", "const char*"}}},
        {"strncat",                   {"char*", {"char*", "const char*", "size_t"}}},
        {"strstr",                    {"char*", {"const char*", "const char*"}}},
        {"strchr",                    {"char*", {"const char*", "int"}}},
        {"strrchr",                   {"char*", {"const char*", "int"}}},
        {"strtok",                    {"char*", {"char*", "const char*"}}},
        {"atoi",                      {"int", {"const char*"}}},
        {"atol",                      {"long", {"const char*"}}},
        {"atoll",                     {"long long", {"const char*"}}},
        {"strtol",                    {"long", {"const char*", "char**", "int"}}},
        {"strtoul",                   {"unsigned long", {"const char*", "char**", "int"}}},
        {"strtod",                    {"double", {"const char*", "char**"}}},
        {"qsort",                     {"void", {"void*", "size_t", "size_t", "int (*)(const void*,const void*)"}}},
        {"bsearch",                   {"void*", {"const void*", "const void*", "size_t", "size_t", "int (*)(const void*,const void*)"}}},
        {"rand",                      {"int", {}}},
        {"srand",                     {"void", {"unsigned int"}}},
        {"time",                      {"time_t", {"time_t*"}}},
        {"clock",                     {"clock_t", {}}},
        {"localtime",                 {"struct tm*", {"const time_t*"}}},
        {"gmtime",                    {"struct tm*", {"const time_t*"}}},
        {"mktime",                    {"time_t", {"struct tm*"}}},
        {"difftime",                  {"double", {"time_t", "time_t"}}},
        {"signal",                    {"void (*)(int)", {"int", "void (*)(int)"}}},
        {"raise",                     {"int", {"int"}}},
        {"setjmp",                    {"int", {"jmp_buf"}}},
        {"assert",                    {"void", {"int"}}},
    };
    return table;
}

const std::unordered_set<std::string>& getNoReturnTable() {
    static const std::unordered_set<std::string> noReturn = {
        "ExitProcess", "TerminateProcess", "abort", "exit", "_exit",
        "quick_exit", "FatalExit", "FatalAppExit", "longjmp",
        "RaiseException", "ExitThread", "FreeLibraryAndExitThread",
    };
    return noReturn;
}

// Include auto-generated extended signature table (inside anonymous namespace)
#include "wintype_siggen.inc"

} // anonymous namespace

class WindowsTypeDatabase : public TypeDatabase {
public:
    bool getFunctionType(const std::string& funcName,
                         std::string& returnType,
                         std::vector<std::string>& paramTypes) const override {
        // Check base table first
        const auto& table = getTypeTable();
        auto it = table.find(funcName);
        if (it != table.end()) {
            returnType = it->second.returnType;
            paramTypes.clear();
            for (const char* p : it->second.paramTypes)
                paramTypes.push_back(p);
            return true;
        }
        // Check auto-generated extended table as fallback
        const auto& ext = getSigGenTable();
        auto eit = ext.find(funcName);
        if (eit == ext.end()) return false;
        returnType = eit->second.returnType;
        paramTypes.clear();
        for (const char* p : eit->second.paramTypes)
            paramTypes.push_back(p);
        return true;
    }

    bool isNoReturn(const std::string& funcName) const override {
        const auto& table = getNoReturnTable();
        return table.find(funcName) != table.end();
    }

    std::string getPlatformName() const override {
        return "Windows";
    }
};

std::unique_ptr<TypeDatabase> createWindowsTypeDatabase() {
    return std::make_unique<WindowsTypeDatabase>();
}

} // namespace ghidra
